window.MADLIB_TEMPLATES = window.MADLIB_TEMPLATES || {};
Object.assign(window.MADLIB_TEMPLATES, {

  great_adventure: {
    title: "The Great Adventure",
    category: "Adventure & Fantasy",
    story: "Once upon a time, a {{ADJ_1}} hero named {{NAME_1}} set out on a {{ADJ_2}} quest to find the legendary {{NOUN_1}} of {{PLACE_1}}. Armed with nothing but a {{ADJ_3}} {{NOUN_2}} and an unwavering desire to {{VERB_1}}, our hero {{VERB_2}} through the {{ADJ_4}} wilderness. Along the way, they encountered a {{ADJ_5}} creature that could only {{VERB_3}} backwards. After a {{ADJ_6}} battle, {{NAME_1}} emerged victorious and returned to {{PLACE_2}} as the most {{ADJ_7}} adventurer who ever lived.",
    fields: [
      { key: "ADJ_1",   label: "Adjective",         hint: "e.g., fearless" },
      { key: "NAME_1",  label: "Hero's name",        hint: "e.g., Gerald" },
      { key: "ADJ_2",   label: "Adjective",          hint: "e.g., dangerous" },
      { key: "NOUN_1",  label: "Noun (treasure)",    hint: "e.g., golden spatula" },
      { key: "PLACE_1", label: "Mystical place",     hint: "e.g., Mount Doom" },
      { key: "ADJ_3",   label: "Adjective",          hint: "e.g., rusty" },
      { key: "NOUN_2",  label: "Weapon or tool",     hint: "e.g., mop" },
      { key: "VERB_1",  label: "Verb (to...)",       hint: "e.g., yodel" },
      { key: "VERB_2",  label: "Past tense verb",    hint: "e.g., stomped" },
      { key: "ADJ_4",   label: "Adjective",          hint: "e.g., swampy" },
      { key: "ADJ_5",   label: "Adjective",          hint: "e.g., three-headed" },
      { key: "VERB_3",  label: "Verb",               hint: "e.g., sneeze" },
      { key: "ADJ_6",   label: "Adjective",          hint: "e.g., epic" },
      { key: "PLACE_2", label: "Home place",         hint: "e.g., Blandsville" },
      { key: "ADJ_7",   label: "Adjective",          hint: "e.g., legendary" },
    ]
  },

  dragon_lair: {
    title: "The Dragon's Lair",
    category: "Adventure & Fantasy",
    story: "Deep inside {{ADJ_1}} Mount {{NOUN_1}}, the {{ADJ_2}} knight {{NAME_1}} crept toward the lair of {{DRAGON_NAME}}, the most {{ADJ_3}} dragon in all the realm. The cave reeked of {{NOUN_2}} and {{NOUN_3}}, and every wall was plastered with {{ADJ_4}} {{NOUN_4}}s. {{NAME_1}} tried to {{VERB_1}} silently but slipped on a puddle of {{NOUN_5}} and tumbled right onto the dragon's {{BODY_PART}}. \"{{EXCLAIM}}!\" the dragon bellowed. But when {{NAME_1}} offered a peace gift of one {{ADJ_5}} {{NOUN_6}}, the dragon burst into {{ADJ_6}} tears and admitted it had always wanted a {{ADJ_7}} friend.",
    fields: [
      { key: "ADJ_1",      label: "Adjective",         hint: "e.g., smoldering" },
      { key: "NOUN_1",     label: "Mountain name",     hint: "e.g., Blorbax" },
      { key: "ADJ_2",      label: "Adjective",         hint: "e.g., trembling" },
      { key: "NAME_1",     label: "Knight's name",     hint: "e.g., Sir Reginald" },
      { key: "DRAGON_NAME",label: "Dragon's name",     hint: "e.g., Flamantha" },
      { key: "ADJ_3",      label: "Adjective",         hint: "e.g., flatulent" },
      { key: "NOUN_2",     label: "Smelly noun",       hint: "e.g., gym socks" },
      { key: "NOUN_3",     label: "Another smelly noun",hint: "e.g., blue cheese" },
      { key: "ADJ_4",      label: "Adjective",         hint: "e.g., scorched" },
      { key: "NOUN_4",     label: "Plural noun",       hint: "e.g., motivational poster" },
      { key: "VERB_1",     label: "Verb",              hint: "e.g., tiptoe" },
      { key: "NOUN_5",     label: "Liquid",            hint: "e.g., dragon drool" },
      { key: "BODY_PART",  label: "Body part",         hint: "e.g., tail" },
      { key: "EXCLAIM",    label: "Exclamation",       hint: "e.g., Great Fireballs" },
      { key: "ADJ_5",      label: "Adjective",         hint: "e.g., glittery" },
      { key: "NOUN_6",     label: "Gift",              hint: "e.g., cheese wheel" },
      { key: "ADJ_6",      label: "Adjective",         hint: "e.g., happy" },
      { key: "ADJ_7",      label: "Adjective",         hint: "e.g., human" },
    ]
  },

  magic_shop: {
    title: "The Mysterious Magic Shop",
    category: "Adventure & Fantasy",
    story: "{{NAME_1}} had always ignored the {{ADJ_1}} little shop at the end of {{STREET_NAME}} Street — until the day it glowed {{COLOR_1}} and began to {{VERB_1}}. Inside, the shopkeeper, an ancient {{NOUN_1}} named {{NAME_2}}, offered three magical items: a {{ADJ_2}} hat that made you {{VERB_2}} uncontrollably, a {{NOUN_2}} that whispered {{ADJ_3}} secrets, and a potion that tasted of {{FOOD_1}} but gave you the ability to {{VERB_3}}. {{NAME_1}} chose the potion and immediately {{VERB_4}} all the way home, where their {{NOUN_3}} stared in {{ADJ_4}} disbelief.",
    fields: [
      { key: "NAME_1",      label: "Customer's name",   hint: "e.g., Meredith" },
      { key: "ADJ_1",       label: "Adjective",         hint: "e.g., dusty" },
      { key: "STREET_NAME", label: "Street name",       hint: "e.g., Pickle" },
      { key: "COLOR_1",     label: "Color",             hint: "e.g., violet" },
      { key: "VERB_1",      label: "Verb",              hint: "e.g., hum" },
      { key: "NOUN_1",      label: "Creature type",     hint: "e.g., badger-person" },
      { key: "NAME_2",      label: "Shopkeeper's name", hint: "e.g., Orb" },
      { key: "ADJ_2",       label: "Adjective",         hint: "e.g., polka-dotted" },
      { key: "VERB_2",      label: "Verb",              hint: "e.g., cluck" },
      { key: "NOUN_2",      label: "Object",            hint: "e.g., spoon" },
      { key: "ADJ_3",       label: "Adjective",         hint: "e.g., embarrassing" },
      { key: "FOOD_1",      label: "Food",              hint: "e.g., beef jerky" },
      { key: "VERB_3",      label: "Verb",              hint: "e.g., fly backwards" },
      { key: "VERB_4",      label: "Past tense verb",   hint: "e.g., cartwheeled" },
      { key: "NOUN_3",      label: "Family member",     hint: "e.g., grandmother" },
      { key: "ADJ_4",       label: "Adjective",         hint: "e.g., horrified" },
    ]
  },

  pirates: {
    title: "Pirates of the Seven Seas",
    category: "Adventure & Fantasy",
    story: "Captain {{NAME_1}}, the most {{ADJ_1}} pirate to ever sail the {{COLOR_1}} sea, stood at the helm of the {{SHIP_NAME}} and pointed a {{ADJ_2}} finger toward the horizon. \"{{EXCLAIM}}, you {{ADJ_3}} crew of {{NOUN_1}}s!\" they bellowed. \"Treasure awaits on the island of {{ISLAND_NAME}}!\" The crew, a ragged bunch who {{VERB_1}}ed for fun, leapt into action. But the island was guarded by a {{ADJ_4}} sea monster that could only be defeated by {{VERB_2}}ing at it really loudly. The treasure turned out to be a chest full of {{NOUN_2}}s — and somehow, that was exactly what everyone needed.",
    fields: [
      { key: "NAME_1",     label: "Captain's name",    hint: "e.g., Pegleg Patricia" },
      { key: "ADJ_1",      label: "Adjective",         hint: "e.g., notorious" },
      { key: "COLOR_1",    label: "Color",             hint: "e.g., teal" },
      { key: "SHIP_NAME",  label: "Ship name",         hint: "e.g., The Soggy Noodle" },
      { key: "ADJ_2",      label: "Adjective",         hint: "e.g., crusty" },
      { key: "EXCLAIM",    label: "Exclamation",       hint: "e.g., Shiver me timbers" },
      { key: "ADJ_3",      label: "Adjective",         hint: "e.g., scurvy" },
      { key: "NOUN_1",     label: "Plural noun",       hint: "e.g., landlubber" },
      { key: "ISLAND_NAME",label: "Island name",       hint: "e.g., Squid Nugget Cay" },
      { key: "VERB_1",     label: "Verb",              hint: "e.g., juggle fish" },
      { key: "ADJ_4",      label: "Adjective",         hint: "e.g., irritable" },
      { key: "VERB_2",     label: "Verb",              hint: "e.g., complain" },
      { key: "NOUN_2",     label: "Plural noun",       hint: "e.g., novelty mug" },
    ]
  },

  wizard_apprentice: {
    title: "The Wizard's Apprentice",
    category: "Adventure & Fantasy",
    story: "On my first day as apprentice to the grand wizard {{WIZARD_NAME}}, I was told never to touch the {{ADJ_1}} {{NOUN_1}} on the third shelf. Naturally, I immediately {{VERB_1}}ed it. The resulting explosion covered the entire tower in {{NOUN_2}} and transformed the wizard's {{PET}} into something {{ADJ_2}}. \"You {{ADJ_3}} {{NOUN_3}}!\" the wizard shrieked, chasing me around the room with a {{ADJ_4}} wand. After three hours of {{VERB_2}}ing, we managed to reverse most of the spell — except now everything in the lab smells faintly of {{FOOD}} and {{NOUN_4}}. The wizard says I have \"{{ADJ_5}} potential.\" I think they meant it as an insult.",
    fields: [
      { key: "WIZARD_NAME",label: "Wizard's name",     hint: "e.g., Glorbadon" },
      { key: "ADJ_1",      label: "Adjective",         hint: "e.g., pulsating" },
      { key: "NOUN_1",     label: "Magic object",      hint: "e.g., orb" },
      { key: "VERB_1",     label: "Past tense verb",   hint: "e.g., sneezed on" },
      { key: "NOUN_2",     label: "Substance",         hint: "e.g., marmalade" },
      { key: "PET",        label: "Pet animal",        hint: "e.g., ferret" },
      { key: "ADJ_2",      label: "Adjective",         hint: "e.g., accordion-shaped" },
      { key: "ADJ_3",      label: "Adjective",         hint: "e.g., bumbling" },
      { key: "NOUN_3",     label: "Insult (noun)",     hint: "e.g., turnip" },
      { key: "ADJ_4",      label: "Adjective",         hint: "e.g., frantic" },
      { key: "VERB_2",     label: "Verb (-ing)",       hint: "e.g., incanting" },
      { key: "FOOD",       label: "Food",              hint: "e.g., tuna casserole" },
      { key: "NOUN_4",     label: "Noun",              hint: "e.g., regret" },
      { key: "ADJ_5",      label: "Adjective",         hint: "e.g., catastrophic" },
    ]
  },

  haunted_castle: {
    title: "The Haunted Castle",
    category: "Adventure & Fantasy",
    story: "The real estate listing described Castle {{CASTLE_NAME}} as \"{{ADJ_1}} and full of character.\" What it failed to mention was the {{ADJ_2}} ghost of Lord {{NAME_1}}, who would {{VERB_1}} through the halls every night screaming about his missing {{NOUN_1}}. Our group of {{NUMBER}} {{ADJ_3}} explorers decided to spend the night anyway. By midnight, the {{NOUN_2}} had started {{VERB_2}}ing on its own, the portraits were {{VERB_3}}ing, and someone's {{NOUN_3}} had been replaced with a {{ADJ_4}} {{NOUN_4}}. We solved the mystery when we discovered the ghost just wanted someone to {{VERB_4}} with him. We played until dawn. He was surprisingly {{ADJ_5}} at it.",
    fields: [
      { key: "CASTLE_NAME",label: "Castle name",       hint: "e.g., Dreadmoor" },
      { key: "ADJ_1",      label: "Adjective",         hint: "e.g., cozy" },
      { key: "ADJ_2",      label: "Adjective",         hint: "e.g., dramatic" },
      { key: "NAME_1",     label: "Ghost's name",      hint: "e.g., Humphrey" },
      { key: "VERB_1",     label: "Verb",              hint: "e.g., float" },
      { key: "NOUN_1",     label: "Prized possession", hint: "e.g., favorite spoon" },
      { key: "NUMBER",     label: "Number",            hint: "e.g., six" },
      { key: "ADJ_3",      label: "Adjective",         hint: "e.g., underprepared" },
      { key: "NOUN_2",     label: "Furniture",         hint: "e.g., chandelier" },
      { key: "VERB_2",     label: "Verb",              hint: "e.g., spin" },
      { key: "VERB_3",     label: "Verb",              hint: "e.g., wink" },
      { key: "NOUN_3",     label: "Personal item",     hint: "e.g., sleeping bag" },
      { key: "ADJ_4",      label: "Adjective",         hint: "e.g., damp" },
      { key: "NOUN_4",     label: "Random object",     hint: "e.g., accordion" },
      { key: "VERB_4",     label: "Verb (game)",       hint: "e.g., play chess" },
      { key: "ADJ_5",      label: "Adjective",         hint: "e.g., competitive" },
    ]
  },

  secret_map: {
    title: "The Secret Treasure Map",
    category: "Adventure & Fantasy",
    story: "{{NAME_1}} found the map inside a {{ADJ_1}} {{NOUN_1}} at a garage sale for {{PRICE}} cents. It was written in {{ADJ_2}} ink and marked a path through the {{PLACE_1}}, past the {{ADJ_3}} {{NOUN_2}}, and to a spot labeled \"{{NOUN_3}} of Legends.\" After three days of {{VERB_1}}ing through {{ADJ_4}} terrain with only a {{NOUN_4}} for company, {{NAME_1}} arrived at the spot and {{VERB_2}}ed until the ground opened up. Inside: a chamber full of {{ADJ_5}} {{NOUN_5}}s and a note that read, \"Congratulations. We {{VERB_3}}ed a long time for someone {{ADJ_6}} enough to find this.\"",
    fields: [
      { key: "NAME_1",  label: "Explorer's name",   hint: "e.g., Dot Figgins" },
      { key: "ADJ_1",   label: "Adjective",         hint: "e.g., waterlogged" },
      { key: "NOUN_1",  label: "Container",         hint: "e.g., biscuit tin" },
      { key: "PRICE",   label: "Small price",       hint: "e.g., 12" },
      { key: "ADJ_2",   label: "Adjective",         hint: "e.g., glowing" },
      { key: "PLACE_1", label: "Natural place",     hint: "e.g., the Boggy Swamp" },
      { key: "ADJ_3",   label: "Adjective",         hint: "e.g., three-legged" },
      { key: "NOUN_2",  label: "Landmark",          hint: "e.g., birdbath" },
      { key: "NOUN_3",  label: "Noun",              hint: "e.g., Chamber" },
      { key: "VERB_1",  label: "Verb (-ing)",       hint: "e.g., stumbling" },
      { key: "ADJ_4",   label: "Adjective",         hint: "e.g., inexplicable" },
      { key: "NOUN_4",  label: "Companion item",    hint: "e.g., fanny pack" },
      { key: "VERB_2",  label: "Past tense verb",   hint: "e.g., stamped" },
      { key: "ADJ_5",   label: "Adjective",         hint: "e.g., bedazzled" },
      { key: "NOUN_5",  label: "Plural noun",       hint: "e.g., recliner" },
      { key: "VERB_3",  label: "Past tense verb",   hint: "e.g., waited" },
      { key: "ADJ_6",   label: "Adjective",         hint: "e.g., peculiar" },
    ]
  },

  time_traveler: {
    title: "The Accidental Time Traveler",
    category: "Adventure & Fantasy",
    story: "It started when {{NAME_1}} {{VERB_1}}ed too hard on the {{ADJ_1}} {{NOUN_1}} and accidentally activated the time machine hidden inside. One {{ADJ_2}} flash later, {{NAME_1}} was standing in {{YEAR}}, surrounded by {{ADJ_3}} {{NOUN_2}}s and people wearing {{ADJ_4}} {{NOUN_3}}s. A local {{OCCUPATION}} named {{NAME_2}} immediately tried to {{VERB_2}} {{NAME_1}}, mistaking them for the prophesied {{ADJ_5}} {{NOUN_4}}. To blend in, {{NAME_1}} had to {{VERB_3}} and pretend to enjoy eating {{FOOD}} every meal. Getting home required convincing a {{ADJ_6}} inventor to build a replacement device out of {{NOUN_5}}, which worked perfectly on the third {{ADJ_7}} attempt.",
    fields: [
      { key: "NAME_1",     label: "Traveler's name",   hint: "e.g., Prudence" },
      { key: "VERB_1",     label: "Past tense verb",   hint: "e.g., sneezed" },
      { key: "ADJ_1",      label: "Adjective",         hint: "e.g., ordinary-looking" },
      { key: "NOUN_1",     label: "Household item",    hint: "e.g., microwave" },
      { key: "ADJ_2",      label: "Adjective",         hint: "e.g., blinding" },
      { key: "YEAR",       label: "Year",              hint: "e.g., 1423" },
      { key: "ADJ_3",      label: "Adjective",         hint: "e.g., bewildered" },
      { key: "NOUN_2",     label: "People (plural)",   hint: "e.g., blacksmith" },
      { key: "ADJ_4",      label: "Adjective",         hint: "e.g., enormous" },
      { key: "NOUN_3",     label: "Clothing item",     hint: "e.g., hat" },
      { key: "OCCUPATION", label: "Job/title",         hint: "e.g., village elder" },
      { key: "NAME_2",     label: "Local's name",      hint: "e.g., Aldric" },
      { key: "VERB_2",     label: "Verb (to...)",      hint: "e.g., worship" },
      { key: "ADJ_5",      label: "Adjective",         hint: "e.g., destined" },
      { key: "NOUN_4",     label: "Legendary title",   hint: "e.g., Cheese Bringer" },
      { key: "VERB_3",     label: "Verb",              hint: "e.g., joust" },
      { key: "FOOD",       label: "Unpleasant food",   hint: "e.g., boiled turnip mush" },
      { key: "ADJ_6",      label: "Adjective",         hint: "e.g., eccentric" },
      { key: "NOUN_5",     label: "Material",          hint: "e.g., pinecones" },
      { key: "ADJ_7",      label: "Adjective",         hint: "e.g., explosive" },
    ]
  },

  lost_kingdom: {
    title: "The Lost Kingdom",
    category: "Adventure & Fantasy",
    story: "The kingdom of {{KINGDOM_NAME}} had been lost for {{NUMBER_1}} centuries, hidden beneath the {{ADJ_1}} {{PLACE_1}} by an ancient curse involving a {{ADJ_2}} {{NOUN_1}}. Explorer {{NAME_1}} discovered it while trying to {{VERB_1}} their way out of a wrong turn. The underground kingdom was {{ADJ_3}} — its citizens had spent centuries {{VERB_2}}ing and developing a civilization based entirely around {{NOUN_2}}. Their queen, a {{ADJ_4}} figure named {{NAME_2}}, immediately offered {{NAME_1}} the title of Grand {{NOUN_3}} in exchange for teaching them how to {{VERB_3}}. {{NAME_1}} accepted, mostly because the kingdom's food was {{ADJ_5}} and they weren't ready to leave.",
    fields: [
      { key: "KINGDOM_NAME",label: "Kingdom name",     hint: "e.g., Subterranea" },
      { key: "NUMBER_1",    label: "Number",           hint: "e.g., four hundred" },
      { key: "ADJ_1",       label: "Adjective",        hint: "e.g., unremarkable" },
      { key: "PLACE_1",     label: "Geographic place", hint: "e.g., parking lot" },
      { key: "ADJ_2",       label: "Adjective",        hint: "e.g., poorly-worded" },
      { key: "NOUN_1",      label: "Object",           hint: "e.g., thimble" },
      { key: "NAME_1",      label: "Explorer's name",  hint: "e.g., Agatha" },
      { key: "VERB_1",      label: "Verb",             hint: "e.g., sneak" },
      { key: "ADJ_3",       label: "Adjective",        hint: "e.g., surprisingly cozy" },
      { key: "VERB_2",      label: "Verb (-ing)",      hint: "e.g., knitting" },
      { key: "NOUN_2",      label: "Hobby/thing",      hint: "e.g., competitive napping" },
      { key: "ADJ_4",       label: "Adjective",        hint: "e.g., imposing" },
      { key: "NAME_2",      label: "Queen's name",     hint: "e.g., Velda" },
      { key: "NOUN_3",      label: "Fancy title",      hint: "e.g., Liaison" },
      { key: "VERB_3",      label: "Verb",             hint: "e.g., parallel park" },
      { key: "ADJ_5",       label: "Adjective",        hint: "e.g., incredible" },
    ]
  },

  knights_quest: {
    title: "The Knight's Quest",
    category: "Adventure & Fantasy",
    story: "Sir {{NAME_1}} of the order of the {{ADJ_1}} {{NOUN_1}} was given a most {{ADJ_2}} quest by King {{NAME_2}}: retrieve the sacred {{NOUN_2}} from the tower of {{PLACE_1}} before the next {{CELESTIAL_EVENT}}. The tower was guarded by a troll who demanded travelers {{VERB_1}} before passing, a riddle-sphinx who only accepted answers involving {{NOUN_3}}, and an enchanted gate that would only open if you {{VERB_2}} politely. After all three trials, Sir {{NAME_1}} found the {{NOUN_2}} sitting on a {{ADJ_3}} shelf next to a half-eaten {{FOOD}}. The note beside it read: \"Took you {{NUMBER}} years. Quite {{ADJ_4}}, really.\"",
    fields: [
      { key: "NAME_1",        label: "Knight's name",    hint: "e.g., Barnabas" },
      { key: "ADJ_1",        label: "Adjective",         hint: "e.g., Wobbly" },
      { key: "NOUN_1",       label: "Order symbol",      hint: "e.g., Spoon" },
      { key: "ADJ_2",        label: "Adjective",         hint: "e.g., urgent" },
      { key: "NAME_2",       label: "King's name",       hint: "e.g., Gerald IV" },
      { key: "NOUN_2",       label: "Sacred object",     hint: "e.g., rubber duck" },
      { key: "PLACE_1",      label: "Tower name",        hint: "e.g., Gloom's Peak" },
      { key: "CELESTIAL_EVENT",label: "Celestial event", hint: "e.g., lunar sneeze" },
      { key: "VERB_1",       label: "Verb",              hint: "e.g., tap dance" },
      { key: "NOUN_3",       label: "Topic",             hint: "e.g., plumbing" },
      { key: "VERB_2",       label: "Verb",              hint: "e.g., curtsy" },
      { key: "ADJ_3",        label: "Adjective",         hint: "e.g., dusty" },
      { key: "FOOD",         label: "Food",              hint: "e.g., hot pocket" },
      { key: "NUMBER",       label: "Number",            hint: "e.g., thirty-seven" },
      { key: "ADJ_4",        label: "Adjective",         hint: "e.g., underwhelming" },
    ]
  },

});
