window.MADLIB_TEMPLATES = window.MADLIB_TEMPLATES || {};
Object.assign(window.MADLIB_TEMPLATES, {

  nature_doc: {
    title: "Nature Documentary",
    category: "Animals & Nature",
    story: "Here in the {{ADJ_1}} {{HABITAT_1}} of {{PLACE_1}}, we observe one of nature's most {{ADJ_2}} creatures: the {{ADJ_3}} {{ANIMAL_1}}. Notice how it {{VERB_1}}s with remarkable {{NOUN_1}} as it searches for its favorite meal — {{FOOD_1}}. The {{ANIMAL_1}} must {{VERB_2}} at least {{NUMBER_1}} times per day to maintain its {{ADJ_4}} physique. But danger lurks. The fearsome {{ANIMAL_2}} — a natural predator — begins to {{VERB_3}} toward it from the {{DIRECTION_1}}. In a breathtaking display of {{NOUN_2}}, the {{ANIMAL_1}} {{VERB_4}}s to safety behind a {{ADJ_5}} {{NOUN_3}}. The predator, now {{ADJ_6}} and {{EMOTION_1}}, {{VERB_5}}s away in defeat. Our hero survives another day in this {{ADJ_7}} world, ready to {{VERB_6}} again tomorrow.",
    fields: [
      { key: "ADJ_1",      label: "Adjective",        hint: "e.g., sun-baked" },
      { key: "HABITAT_1",  label: "Habitat",          hint: "e.g., rainforest" },
      { key: "PLACE_1",    label: "Place",            hint: "e.g., Borneo" },
      { key: "ADJ_2",      label: "Adjective",        hint: "e.g., misunderstood" },
      { key: "ADJ_3",      label: "Adjective",        hint: "e.g., magnificent" },
      { key: "ANIMAL_1",   label: "Animal",           hint: "e.g., pangolin" },
      { key: "VERB_1",     label: "Verb",             hint: "e.g., amble" },
      { key: "NOUN_1",     label: "Noun (quality)",   hint: "e.g., grace" },
      { key: "FOOD_1",     label: "Food",             hint: "e.g., termites" },
      { key: "VERB_2",     label: "Verb",             hint: "e.g., sniff" },
      { key: "NUMBER_1",   label: "Number",           hint: "e.g., forty-seven" },
      { key: "ADJ_4",      label: "Adjective",        hint: "e.g., impressive" },
      { key: "ANIMAL_2",   label: "Predator animal",  hint: "e.g., jaguar" },
      { key: "VERB_3",     label: "Verb",             hint: "e.g., creep" },
      { key: "DIRECTION_1",label: "Direction",        hint: "e.g., north" },
      { key: "NOUN_2",     label: "Noun (quality)",   hint: "e.g., agility" },
      { key: "VERB_4",     label: "Verb",             hint: "e.g., scramble" },
      { key: "ADJ_5",      label: "Adjective",        hint: "e.g., rotting" },
      { key: "NOUN_3",     label: "Natural object",   hint: "e.g., boulder" },
      { key: "ADJ_6",      label: "Adjective",        hint: "e.g., famished" },
      { key: "EMOTION_1",  label: "Emotion",          hint: "e.g., dejected" },
      { key: "VERB_5",     label: "Past tense verb",  hint: "e.g., slunk" },
      { key: "ADJ_7",      label: "Adjective",        hint: "e.g., unpredictable" },
      { key: "VERB_6",     label: "Verb",             hint: "e.g., forage" },
    ]
  },

  dog_park: {
    title: "Dog Park Drama",
    category: "Animals & Nature",
    story: "Every Saturday, the {{PARK_NAME}} Dog Park becomes a {{ADJ_1}} social battleground. {{DOG_NAME_1}}, a {{ADJ_2}} {{BREED_1}}, arrived first and immediately began {{VERB_1}}ing on everything to establish dominance. Then {{DOG_NAME_2}} — a {{ADJ_3}} {{BREED_2}} with an attitude — {{VERB_2}}ed through the gate. Their owners, {{OWNER_1}} and {{OWNER_2}}, pretended to be {{ADJ_4}} while desperately {{VERB_3}}ing their dogs away from the {{NOUN_1}} situation developing near the water fountain. The real drama began when {{DOG_NAME_3}}, a {{ADJ_5}} {{BREED_3}}, {{VERB_4}}ed the communal tennis ball and refused to give it back for {{NUMBER}} minutes. Peace was restored only when someone dropped a {{FOOD}}, at which point every dog became immediate best friends.",
    fields: [
      { key: "PARK_NAME",  label: "Park name",        hint: "e.g., Meadowbrook" },
      { key: "ADJ_1",      label: "Adjective",        hint: "e.g., elaborate" },
      { key: "DOG_NAME_1", label: "Dog's name",       hint: "e.g., Sir Barksalot" },
      { key: "ADJ_2",      label: "Adjective",        hint: "e.g., pompous" },
      { key: "BREED_1",    label: "Dog breed",        hint: "e.g., corgi" },
      { key: "VERB_1",     label: "Verb (-ing)",      hint: "e.g., sniffing" },
      { key: "DOG_NAME_2", label: "Second dog's name",hint: "e.g., Princess Flufferton" },
      { key: "ADJ_3",      label: "Adjective",        hint: "e.g., haughty" },
      { key: "BREED_2",    label: "Dog breed",        hint: "e.g., dachshund" },
      { key: "VERB_2",     label: "Past tense verb",  hint: "e.g., strutted" },
      { key: "OWNER_1",    label: "First owner name", hint: "e.g., Karen" },
      { key: "OWNER_2",    label: "Second owner name",hint: "e.g., Todd" },
      { key: "ADJ_4",      label: "Adjective",        hint: "e.g., completely calm" },
      { key: "VERB_3",     label: "Verb (-ing)",      hint: "e.g., desperately tugging" },
      { key: "NOUN_1",     label: "Awkward noun",     hint: "e.g., territorial standoff" },
      { key: "DOG_NAME_3", label: "Third dog's name", hint: "e.g., Chompers McGee" },
      { key: "ADJ_5",      label: "Adjective",        hint: "e.g., suspiciously calm" },
      { key: "BREED_3",    label: "Dog breed",        hint: "e.g., golden retriever" },
      { key: "VERB_4",     label: "Past tense verb",  hint: "e.g., commandeered" },
      { key: "NUMBER",     label: "Number of minutes",hint: "e.g., forty-five" },
      { key: "FOOD",       label: "Food dropped",     hint: "e.g., a hot dog" },
    ]
  },

  zoo_escape: {
    title: "The Great Zoo Escape",
    category: "Animals & Nature",
    story: "It began at {{TIME_1}} when {{ANIMAL_1_NAME}}, the {{ADJ_1}} {{ANIMAL_1}}, discovered that someone had left the gate {{ADJ_2}}. By {{TIME_2}}, a coalition of {{NUMBER_1}} animals had formed under the leadership of {{ANIMAL_2_NAME}}, a {{ADJ_3}} {{ANIMAL_2}} with a reputation for {{VERB_1}}ing. Their first objective was the {{ADJ_4}} snack kiosk, where {{NUMBER_2}} pounds of {{FOOD}} awaited. The zookeeper, {{NAME_1}}, gave chase on a {{VERB_2}}ing golf cart while {{VERB_3}}ing into a walkie-talkie. Three {{ANIMAL_3}}s got as far as the {{PLACE_1}} before a {{ADJ_5}} child offered them {{FOOD_2}} and they completely forgot the plan. The last animal was returned to its habitat at {{TIME_3}}, looking {{ADJ_6}} but satisfied.",
    fields: [
      { key: "TIME_1",      label: "Time of day",      hint: "e.g., 9:47 AM" },
      { key: "ANIMAL_1_NAME",label: "Animal 1 name",   hint: "e.g., Gerald" },
      { key: "ADJ_1",       label: "Adjective",        hint: "e.g., scheming" },
      { key: "ANIMAL_1",    label: "Animal type",      hint: "e.g., capybara" },
      { key: "ADJ_2",       label: "Adjective",        hint: "e.g., suspiciously open" },
      { key: "TIME_2",      label: "Later time",       hint: "e.g., 10:15 AM" },
      { key: "NUMBER_1",    label: "Number of animals",hint: "e.g., seven" },
      { key: "ANIMAL_2_NAME",label: "Ringleader name", hint: "e.g., Moneybags" },
      { key: "ADJ_3",       label: "Adjective",        hint: "e.g., strategic" },
      { key: "ANIMAL_2",    label: "Animal type",      hint: "e.g., sea otter" },
      { key: "VERB_1",      label: "Verb (-ing)",      hint: "e.g., plotting" },
      { key: "ADJ_4",       label: "Adjective",        hint: "e.g., unguarded" },
      { key: "FOOD",        label: "Snack food",       hint: "e.g., churros" },
      { key: "NAME_1",      label: "Zookeeper name",   hint: "e.g., Hank" },
      { key: "VERB_2",      label: "Verb (-ing)",      hint: "e.g., sputtering" },
      { key: "VERB_3",      label: "Verb (-ing)",      hint: "e.g., shouting" },
      { key: "ANIMAL_3",    label: "Another animal",   hint: "e.g., penguins" },
      { key: "PLACE_1",     label: "Zoo area",         hint: "e.g., gift shop" },
      { key: "ADJ_5",       label: "Adjective",        hint: "e.g., enthusiastic" },
      { key: "FOOD_2",      label: "Second food",      hint: "e.g., cotton candy" },
      { key: "TIME_3",      label: "Final time",       hint: "e.g., 4:30 PM" },
      { key: "ADJ_6",       label: "Adjective",        hint: "e.g., slightly smug" },
    ]
  },

  vet_visit: {
    title: "The Veterinary Visit",
    category: "Animals & Nature",
    story: "{{PET_NAME}} the {{ADJ_1}} {{PET_TYPE}} somehow knew it was vet day and began {{VERB_1}}ing behind the {{NOUN_1}} at exactly {{TIME}}. Owner {{NAME_1}} spent {{NUMBER_1}} minutes {{VERB_2}}ing before resorting to bribes of {{FOOD}}. At the clinic, Dr. {{VET_NAME}} attempted a routine checkup but {{PET_NAME}} immediately {{VERB_3}}ed onto the {{ADJ_2}} equipment, knocking over {{NUMBER_2}} things and {{VERB_4}}ing at the thermometer. \"Your pet is {{ADJ_3}},\" Dr. {{VET_NAME}} announced, {{ADJ_4}}ly. \"But I'd recommend {{VERB_5}}ing twice daily and limiting {{NOUN_2}}.\" {{NAME_1}} nodded as if this made sense. Back in the car, {{PET_NAME}} sat in the passenger seat looking {{ADJ_5}} and absolutely refused to {{VERB_6}} about it.",
    fields: [
      { key: "PET_NAME",  label: "Pet's name",        hint: "e.g., Tornado" },
      { key: "ADJ_1",     label: "Adjective",         hint: "e.g., allegedly innocent" },
      { key: "PET_TYPE",  label: "Type of pet",       hint: "e.g., cat" },
      { key: "VERB_1",    label: "Verb (-ing)",       hint: "e.g., hiding" },
      { key: "NOUN_1",    label: "Furniture",         hint: "e.g., refrigerator" },
      { key: "TIME",      label: "Time",              hint: "e.g., 7:23 AM" },
      { key: "NAME_1",    label: "Owner's name",      hint: "e.g., Marcus" },
      { key: "NUMBER_1",  label: "Minutes spent",     hint: "e.g., twenty-two" },
      { key: "VERB_2",    label: "Verb (-ing)",       hint: "e.g., negotiating" },
      { key: "FOOD",      label: "Treat",             hint: "e.g., turkey bits" },
      { key: "VET_NAME",  label: "Vet's name",        hint: "e.g., Dr. Fluffington" },
      { key: "VERB_3",    label: "Past tense verb",   hint: "e.g., launched" },
      { key: "ADJ_2",     label: "Adjective",         hint: "e.g., expensive-looking" },
      { key: "NUMBER_2",  label: "Number of things",  hint: "e.g., three" },
      { key: "VERB_4",    label: "Verb (-ing)",       hint: "e.g., growling" },
      { key: "ADJ_3",     label: "Health verdict",    hint: "e.g., perfectly healthy" },
      { key: "ADJ_4",     label: "Adjective",         hint: "e.g., cautiously" },
      { key: "VERB_5",    label: "Verb",              hint: "e.g., stretching" },
      { key: "NOUN_2",    label: "Activity",          hint: "e.g., midnight zoomies" },
      { key: "ADJ_5",     label: "Adjective",         hint: "e.g., vindicated" },
      { key: "VERB_6",    label: "Verb",              hint: "e.g., talk" },
    ]
  },

  squirrel_drama: {
    title: "Backyard Squirrel Soap Opera",
    category: "Animals & Nature",
    story: "This fall, the oak tree at {{ADDRESS}} is the setting for the most {{ADJ_1}} rivalry in the neighborhood. {{SQUIRREL_1}}, a {{ADJ_2}} squirrel who has {{VERB_1}}ed over {{NUMBER_1}} acorns, suspects that {{SQUIRREL_2}} — a {{ADJ_3}} newcomer from {{PLACE_1}} — has been {{VERB_2}}ing into their territory. What {{SQUIRREL_2}} doesn't know is that {{SQUIRREL_3}}, the most {{ADJ_4}} squirrel on the block, has been {{VERB_3}}ing information to both sides. The feud escalated when {{SQUIRREL_1}}'s prized stash — {{NUMBER_2}} {{ADJ_5}} {{NOUN_1}}s — was discovered {{VERB_4}}ed behind the {{NOUN_2}}. The neighborhood birds watched from the {{ADJ_6}} branches, {{VERB_5}}ing with {{EMOTION}}. Nobody expected the dramatic finale: everyone was distracted by a human dropping {{FOOD}}, and all grudges were {{ADJ_7}}ly forgotten.",
    fields: [
      { key: "ADDRESS",    label: "Street address",   hint: "e.g., 47 Elm Street" },
      { key: "ADJ_1",      label: "Adjective",        hint: "e.g., elaborate" },
      { key: "SQUIRREL_1", label: "Squirrel 1 name",  hint: "e.g., Chester" },
      { key: "ADJ_2",      label: "Adjective",        hint: "e.g., territorial" },
      { key: "VERB_1",     label: "Past tense verb",  hint: "e.g., hoarded" },
      { key: "NUMBER_1",   label: "Number of acorns", hint: "e.g., four hundred" },
      { key: "SQUIRREL_2", label: "Squirrel 2 name",  hint: "e.g., Vivienne" },
      { key: "ADJ_3",      label: "Adjective",        hint: "e.g., suspicious" },
      { key: "PLACE_1",    label: "Origin place",     hint: "e.g., the park three blocks over" },
      { key: "VERB_2",     label: "Verb (-ing)",      hint: "e.g., encroaching" },
      { key: "SQUIRREL_3", label: "Squirrel 3 name",  hint: "e.g., Reginald" },
      { key: "ADJ_4",      label: "Adjective",        hint: "e.g., devious" },
      { key: "VERB_3",     label: "Verb (-ing)",      hint: "e.g., leaking" },
      { key: "NUMBER_2",   label: "Number",           hint: "e.g., seventy-two" },
      { key: "ADJ_5",      label: "Adjective",        hint: "e.g., prized" },
      { key: "NOUN_1",     label: "Stash contents",   hint: "e.g., walnut" },
      { key: "VERB_4",     label: "Past tense verb",  hint: "e.g., stashed" },
      { key: "NOUN_2",     label: "Hiding spot",      hint: "e.g., garden gnome" },
      { key: "ADJ_6",      label: "Adjective",        hint: "e.g., judgmental" },
      { key: "VERB_5",     label: "Verb (-ing)",      hint: "e.g., gossiping" },
      { key: "EMOTION",    label: "Emotion",          hint: "e.g., great interest" },
      { key: "FOOD",       label: "Dropped food",     hint: "e.g., a hot dog bun" },
      { key: "ADJ_7",      label: "Adjective",        hint: "e.g., completely" },
    ]
  },

  bird_migration: {
    title: "The Great Bird Migration",
    category: "Animals & Nature",
    story: "Every year, the flock of {{NUMBER_1}} {{ADJ_1}} {{BIRD_SPECIES}} sets out from {{PLACE_1}} to fly {{NUMBER_2}} miles south. This year, the flock's navigator, {{BIRD_NAME}}, was {{VERB_1}}ing so confidently that nobody noticed they had taken a {{ADJ_2}} wrong turn somewhere near {{CITY_1}}. By day {{NUMBER_3}}, they were flying over {{PLACE_2}} — which was {{DIRECTION}} of where they needed to be. The elder bird, {{BIRD_NAME_2}}, tried to {{VERB_2}} a correction, but {{BIRD_NAME}} insisted that this route offered {{ADJ_3}} updrafts and {{ADJ_4}} {{NOUN_1}} views. The flock eventually arrived {{NUMBER_4}} days late, {{ADJ_5}}, and slightly {{VERB_3}}ed, at a {{NOUN_2}} in {{PLACE_3}} that was not their traditional wintering ground but had {{ADJ_6}} {{FOOD}} and unanimously agreed it was better anyway.",
    fields: [
      { key: "NUMBER_1",   label: "Flock size",       hint: "e.g., three hundred" },
      { key: "ADJ_1",      label: "Adjective",        hint: "e.g., overconfident" },
      { key: "BIRD_SPECIES",label: "Bird species",    hint: "e.g., Canada geese" },
      { key: "PLACE_1",    label: "Starting place",   hint: "e.g., Minnesota" },
      { key: "NUMBER_2",   label: "Miles to fly",     hint: "e.g., two thousand" },
      { key: "BIRD_NAME",  label: "Navigator bird",   hint: "e.g., Gerald" },
      { key: "VERB_1",     label: "Verb (-ing)",      hint: "e.g., honking" },
      { key: "ADJ_2",      label: "Adjective",        hint: "e.g., catastrophic" },
      { key: "CITY_1",     label: "City name",        hint: "e.g., Omaha" },
      { key: "NUMBER_3",   label: "Day number",       hint: "e.g., four" },
      { key: "PLACE_2",    label: "Wrong place",      hint: "e.g., Wyoming" },
      { key: "DIRECTION",  label: "Direction",        hint: "e.g., northwest" },
      { key: "BIRD_NAME_2",label: "Elder bird",       hint: "e.g., Mavis" },
      { key: "VERB_2",     label: "Verb",             hint: "e.g., squawk" },
      { key: "ADJ_3",      label: "Adjective",        hint: "e.g., exceptional" },
      { key: "ADJ_4",      label: "Adjective",        hint: "e.g., scenic" },
      { key: "NOUN_1",     label: "View type",        hint: "e.g., parking lot" },
      { key: "NUMBER_4",   label: "Days late",        hint: "e.g., eleven" },
      { key: "ADJ_5",      label: "Adjective",        hint: "e.g., exhausted" },
      { key: "VERB_3",     label: "Past tense verb",  hint: "e.g., disoriented" },
      { key: "NOUN_2",     label: "Landing spot",     hint: "e.g., golf course" },
      { key: "PLACE_3",    label: "Final destination",hint: "e.g., New Jersey" },
      { key: "ADJ_6",      label: "Adjective",        hint: "e.g., excellent" },
      { key: "FOOD",       label: "Food there",       hint: "e.g., French fries" },
    ]
  },

  pet_talent_show: {
    title: "The Neighborhood Pet Talent Show",
    category: "Animals & Nature",
    story: "The annual {{NEIGHBORHOOD}} Pet Talent Show featured {{NUMBER_1}} competitors, but everyone knew the real battle was between {{PET_NAME_1}} the {{ANIMAL_1}} and {{PET_NAME_2}} the {{ANIMAL_2}}. {{PET_NAME_1}} opened with a {{ADJ_1}} routine involving a {{NOUN_1}} and {{NUMBER_2}} {{VERB_1}}s that got {{NUMBER_3}} seconds of {{ADJ_2}} applause. {{PET_NAME_2}} followed with an act described simply as \"{{ACT_NAME}},\" during which the judges collectively {{VERB_2}}ed and the audience refused to {{VERB_3}} for {{NUMBER_4}} minutes. The winner, announced by the {{ADJ_3}} host {{NAME_1}}, was neither — it was {{PET_NAME_3}}, a {{ANIMAL_3}} who had fallen asleep onstage in such a {{ADJ_4}} way that everyone agreed it was the most {{ADJ_5}} performance of the evening.",
    fields: [
      { key: "NEIGHBORHOOD",label: "Neighborhood name",hint: "e.g., Maple Grove" },
      { key: "NUMBER_1",    label: "Number of pets",  hint: "e.g., twelve" },
      { key: "PET_NAME_1",  label: "Pet 1 name",      hint: "e.g., Biscuit" },
      { key: "ANIMAL_1",    label: "Animal type 1",   hint: "e.g., beagle" },
      { key: "PET_NAME_2",  label: "Pet 2 name",      hint: "e.g., Countess Von Purr" },
      { key: "ANIMAL_2",    label: "Animal type 2",   hint: "e.g., Persian cat" },
      { key: "ADJ_1",       label: "Adjective",       hint: "e.g., athletic" },
      { key: "NOUN_1",      label: "Prop",            hint: "e.g., hula hoop" },
      { key: "NUMBER_2",    label: "Number of tricks",hint: "e.g., three" },
      { key: "VERB_1",      label: "Verb (trick)",    hint: "e.g., backflip" },
      { key: "NUMBER_3",    label: "Seconds of clapping",hint: "e.g., forty-five" },
      { key: "ADJ_2",       label: "Adjective",       hint: "e.g., confused" },
      { key: "ACT_NAME",    label: "Act name",        hint: "e.g., Chaos Incarnate" },
      { key: "VERB_2",      label: "Past tense verb", hint: "e.g., gasped" },
      { key: "VERB_3",      label: "Verb",            hint: "e.g., blink" },
      { key: "NUMBER_4",    label: "Minutes",         hint: "e.g., seven" },
      { key: "ADJ_3",       label: "Adjective",       hint: "e.g., overwhelmed" },
      { key: "NAME_1",      label: "Host's name",     hint: "e.g., Janet" },
      { key: "PET_NAME_3",  label: "Winning pet",     hint: "e.g., Lord Napsworth" },
      { key: "ANIMAL_3",    label: "Winning animal",  hint: "e.g., guinea pig" },
      { key: "ADJ_4",       label: "Adjective",       hint: "e.g., photogenic" },
      { key: "ADJ_5",       label: "Adjective",       hint: "e.g., artistic" },
    ]
  },

});
