window.MADLIB_TEMPLATES = window.MADLIB_TEMPLATES || {};
Object.assign(window.MADLIB_TEMPLATES, {

  chef_disaster: {
    title: "Celebrity Chef Disaster",
    category: "Food & Cooking",
    story: "Welcome to {{SHOW_1}}, the hottest cooking show on {{CHANNEL_1}}! Today, our celebrity chef {{NAME_1}} will attempt to create a {{ADJ_1}} {{DISH_1}} infused with the essence of {{INGREDIENT_1}}. \"First,\" says {{NAME_1}} in their signature {{ADJ_2}} accent, \"we need to {{VERB_1}} the {{INGREDIENT_2}} until it turns {{COLOR_1}}.\" Things take a turn when the {{NOUN_1}} begins to {{VERB_2}} at {{ADJ_3}} speeds. \"{{EXCLAIM_1}}!\" shouts the chef, as {{INGREDIENT_3}} {{VERB_3}} all over the {{ADJ_4}} studio ceiling. The judges — a {{ADJ_5}} food critic, a {{ADJ_6}} grandmother, and a surprisingly {{ADJ_7}} {{ANIMAL_1}} — watch with {{EMOTION_1}} expressions. Despite the chaos, the final dish tastes {{ADJ_8}}, and {{NAME_1}} is awarded the coveted {{ADJ_9}} Spatula award.",
    fields: [
      { key: "SHOW_1",      label: "Show name",        hint: "e.g., Sizzle Madness" },
      { key: "CHANNEL_1",   label: "TV channel",       hint: "e.g., Channel 7" },
      { key: "NAME_1",      label: "Chef's name",      hint: "e.g., Chef Bloberto" },
      { key: "ADJ_1",       label: "Adjective",        hint: "e.g., revolutionary" },
      { key: "DISH_1",      label: "Dish name",        hint: "e.g., soufflé" },
      { key: "INGREDIENT_1",label: "Ingredient",       hint: "e.g., pickle juice" },
      { key: "ADJ_2",       label: "Adjective",        hint: "e.g., squeaky" },
      { key: "VERB_1",      label: "Cooking verb",     hint: "e.g., sauté" },
      { key: "INGREDIENT_2",label: "Ingredient",       hint: "e.g., mushrooms" },
      { key: "COLOR_1",     label: "Color",            hint: "e.g., iridescent" },
      { key: "NOUN_1",      label: "Kitchen tool",     hint: "e.g., blender" },
      { key: "VERB_2",      label: "Verb",             hint: "e.g., explode" },
      { key: "ADJ_3",       label: "Adjective",        hint: "e.g., terrifying" },
      { key: "EXCLAIM_1",   label: "Exclamation",      hint: "e.g., Mon dieu" },
      { key: "INGREDIENT_3",label: "Ingredient",       hint: "e.g., hollandaise" },
      { key: "VERB_3",      label: "Past tense verb",  hint: "e.g., splattered" },
      { key: "ADJ_4",       label: "Adjective",        hint: "e.g., newly renovated" },
      { key: "ADJ_5",       label: "Adjective",        hint: "e.g., pompous" },
      { key: "ADJ_6",       label: "Adjective",        hint: "e.g., opinionated" },
      { key: "ADJ_7",       label: "Adjective",        hint: "e.g., distinguished" },
      { key: "ANIMAL_1",    label: "Animal",           hint: "e.g., capybara" },
      { key: "EMOTION_1",   label: "Emotion",          hint: "e.g., bewildered" },
      { key: "ADJ_8",       label: "Adjective",        hint: "e.g., transcendent" },
      { key: "ADJ_9",       label: "Adjective",        hint: "e.g., Golden" },
    ]
  },

  birthday_cake: {
    title: "The Birthday Cake Catastrophe",
    category: "Food & Cooking",
    story: "{{NAME_1}} had {{NUMBER_1}} hours to bake a {{ADJ_1}} birthday cake for {{NAME_2}}'s party, which starts in — oh no — {{NUMBER_2}} minutes. The recipe called for {{NUMBER_3}} cups of {{INGREDIENT_1}}, a {{ADJ_2}} dash of {{INGREDIENT_2}}, and \"{{BAKING_INSTRUCTION}}.\" After {{NAME_1}} {{VERB_1}}ed the wrong bowl, the batter turned {{COLOR}} and began to {{VERB_2}}. The oven, set to {{TEMPERATURE}} degrees instead of {{TEMPERATURE_2}}, made things {{ADJ_3}}. When the smoke alarm {{VERB_3}}ed, the dog ate the backup {{NOUN_1}}. The final cake was {{ADJ_4}}, lopsided, and frosted in {{INGREDIENT_3}}, but {{NAME_2}} declared it the most {{ADJ_5}} cake they'd ever seen — which everyone agreed was technically true.",
    fields: [
      { key: "NAME_1",          label: "Baker's name",      hint: "e.g., Margot" },
      { key: "NUMBER_1",        label: "Hours to bake",     hint: "e.g., two" },
      { key: "ADJ_1",           label: "Adjective",         hint: "e.g., three-layer" },
      { key: "NAME_2",          label: "Birthday person",   hint: "e.g., Grandpa Bill" },
      { key: "NUMBER_2",        label: "Minutes left",      hint: "e.g., forty-five" },
      { key: "NUMBER_3",        label: "Number of cups",    hint: "e.g., seven" },
      { key: "INGREDIENT_1",    label: "Ingredient",        hint: "e.g., flour" },
      { key: "ADJ_2",           label: "Adjective",         hint: "e.g., generous" },
      { key: "INGREDIENT_2",    label: "Ingredient",        hint: "e.g., vanilla" },
      { key: "BAKING_INSTRUCTION",label: "Baking instruction",hint: "e.g., fold gently until it speaks" },
      { key: "VERB_1",          label: "Past tense verb",   hint: "e.g., knocked over" },
      { key: "COLOR",           label: "Color",             hint: "e.g., alarming gray" },
      { key: "VERB_2",          label: "Verb",              hint: "e.g., bubble aggressively" },
      { key: "TEMPERATURE",     label: "Wrong temperature", hint: "e.g., 500" },
      { key: "TEMPERATURE_2",   label: "Right temperature", hint: "e.g., 350" },
      { key: "ADJ_3",           label: "Adjective",         hint: "e.g., significantly worse" },
      { key: "VERB_3",          label: "Past tense verb",   hint: "e.g., shrieked" },
      { key: "NOUN_1",          label: "Backup item",       hint: "e.g., store-bought cupcake" },
      { key: "ADJ_4",           label: "Adjective",         hint: "e.g., structurally questionable" },
      { key: "INGREDIENT_3",    label: "Frosting ingredient",hint: "e.g., ketchup" },
      { key: "ADJ_5",           label: "Adjective",         hint: "e.g., unique" },
    ]
  },

  restaurant_review: {
    title: "The Five-Star Restaurant Review",
    category: "Food & Cooking",
    story: "{{REVIEWER}} here, reviewing {{RESTAURANT_NAME}} — the {{ADJ_1}} new establishment on {{STREET}} Street. Upon arrival, the host — a {{ADJ_2}} individual named {{HOST_NAME}} — seated me near the {{ADJ_3}} {{NOUN_1}}, which set the {{ADJ_4}} tone. The amuse-bouche was a single {{FOOD_1}} served on a {{ADJ_5}} {{NOUN_2}} with the word \"{{PRETENTIOUS_WORD}}\" written in {{INGREDIENT}} foam. For my main course, I ordered the \"{{DISH_NAME}},\" which arrived inside a {{NOUN_3}} and tasted of {{FLAVOR_1}} with faint notes of {{FLAVOR_2}} — or possibly {{FLAVOR_3}}. The sommelier, {{SOMMELIER_NAME}}, recommended a {{ADJ_6}} {{NOUN_4}} that paired {{ADJ_7}}ly with my growing {{EMOTION}}. I award this restaurant {{NUMBER}} out of ten {{NOUN_5}}s.",
    fields: [
      { key: "REVIEWER",       label: "Reviewer name",    hint: "e.g., Reginald Snoot" },
      { key: "RESTAURANT_NAME",label: "Restaurant name",  hint: "e.g., Le Fromage Tragique" },
      { key: "ADJ_1",          label: "Adjective",        hint: "e.g., pretentious" },
      { key: "STREET",         label: "Street name",      hint: "e.g., Desolation" },
      { key: "ADJ_2",          label: "Adjective",        hint: "e.g., condescending" },
      { key: "HOST_NAME",      label: "Host's name",      hint: "e.g., Jacques" },
      { key: "ADJ_3",          label: "Adjective",        hint: "e.g., weeping" },
      { key: "NOUN_1",         label: "Decorative item",  hint: "e.g., abstract sculpture" },
      { key: "ADJ_4",          label: "Adjective",        hint: "e.g., unsettling" },
      { key: "FOOD_1",         label: "Tiny food",        hint: "e.g., microgreen" },
      { key: "ADJ_5",          label: "Adjective",        hint: "e.g., hand-foraged" },
      { key: "NOUN_2",         label: "Serving vessel",   hint: "e.g., thimble" },
      { key: "PRETENTIOUS_WORD",label: "Fancy word",      hint: "e.g., Terroir" },
      { key: "INGREDIENT",     label: "Ingredient",       hint: "e.g., truffle" },
      { key: "DISH_NAME",      label: "Dish name",        hint: "e.g., Deconstructed Regret" },
      { key: "NOUN_3",         label: "Container",        hint: "e.g., overturned spoon" },
      { key: "FLAVOR_1",       label: "First flavor",     hint: "e.g., sadness" },
      { key: "FLAVOR_2",       label: "Second flavor",    hint: "e.g., Tuesday" },
      { key: "FLAVOR_3",       label: "Third flavor",     hint: "e.g., old notebook" },
      { key: "SOMMELIER_NAME", label: "Sommelier name",   hint: "e.g., Dominique" },
      { key: "ADJ_6",          label: "Adjective",        hint: "e.g., ethereal" },
      { key: "NOUN_4",         label: "Wine type",        hint: "e.g., Bordeaux" },
      { key: "ADJ_7",          label: "Adjective",        hint: "e.g., inexplicably" },
      { key: "EMOTION",        label: "Emotion",          hint: "e.g., existential dread" },
      { key: "NUMBER",         label: "Score out of ten", hint: "e.g., three" },
      { key: "NOUN_5",         label: "Rating symbol",    hint: "e.g., spoon" },
    ]
  },

  potluck: {
    title: "The Potluck Disaster",
    category: "Food & Cooking",
    story: "{{NAME_1}} had volunteered to bring the {{DISH_TYPE}} to the office potluck before realizing they had never actually {{VERB_1}}ed before. The recipe they found online was titled \"{{RECIPE_NAME}}\" and required {{NUMBER_1}} ingredients they'd never heard of, including {{INGREDIENT_1}}, {{INGREDIENT_2}}, and something called \"{{FAKE_INGREDIENT}}.\" The {{ADJ_1}} result smelled of {{SMELL}} and had a {{ADJ_2}} texture. At the potluck, {{NAME_1}} placed it confidently next to {{COWORKER}}'s {{ADJ_3}} {{DISH_2}} and waited. {{COWORKER_2}} was the first brave soul to try it. Their face cycled through {{NUMBER_2}} distinct expressions before settling on \"{{EXPRESSION}}.\" By some {{ADJ_4}} miracle, three people asked for the recipe. {{NAME_1}} has not spoken to those people since.",
    fields: [
      { key: "NAME_1",        label: "Cook's name",      hint: "e.g., Darren" },
      { key: "DISH_TYPE",     label: "Type of dish",     hint: "e.g., casserole" },
      { key: "VERB_1",        label: "Past tense verb",  hint: "e.g., cooked" },
      { key: "RECIPE_NAME",   label: "Recipe title",     hint: "e.g., Nana's Comfort Surprise" },
      { key: "NUMBER_1",      label: "Number of ingredients",hint: "e.g., seventeen" },
      { key: "INGREDIENT_1",  label: "Ingredient 1",     hint: "e.g., miso paste" },
      { key: "INGREDIENT_2",  label: "Ingredient 2",     hint: "e.g., pomegranate molasses" },
      { key: "FAKE_INGREDIENT",label: "Made-up ingredient",hint: "e.g., dragon fruit reduction" },
      { key: "ADJ_1",         label: "Adjective",        hint: "e.g., glistening" },
      { key: "SMELL",         label: "What it smells like",hint: "e.g., ambition and regret" },
      { key: "ADJ_2",         label: "Adjective",        hint: "e.g., gelatinous" },
      { key: "COWORKER",      label: "Coworker name",    hint: "e.g., Janet" },
      { key: "ADJ_3",         label: "Adjective",        hint: "e.g., professionally prepared" },
      { key: "DISH_2",        label: "Coworker's dish",  hint: "e.g., lasagna" },
      { key: "COWORKER_2",    label: "Second coworker",  hint: "e.g., Gary" },
      { key: "NUMBER_2",      label: "Number of expressions",hint: "e.g., seven" },
      { key: "EXPRESSION",    label: "Facial expression",hint: "e.g., acceptance" },
      { key: "ADJ_4",         label: "Adjective",        hint: "e.g., inexplicable" },
    ]
  },

  grandmas_recipe: {
    title: "Grandma's Secret Recipe",
    category: "Food & Cooking",
    story: "Grandma {{GRANDMA_NAME}}'s famous {{DISH}} had been made at every {{OCCASION}} for {{NUMBER_1}} years, but she had never written the recipe down. On her deathbed — she was fine, just very {{ADJ_1}} — she dictated it to {{NAME_1}}: \"{{AMOUNT_1}} handfuls of {{INGREDIENT_1}}, cook it until it smells like {{SMELL}}, then add {{INGREDIENT_2}} when the {{NOUN_1}} starts to {{VERB_1}}.\" Step three was simply \"you'll know.\" {{NAME_1}} attempted the recipe {{NUMBER_2}} times. Batch one {{VERB_2}}ed. Batch two turned {{COLOR}} and {{VERB_3}}ed for eleven minutes. Batch {{NUMBER_3}} was {{ADJ_2}}, then inexplicably {{ADJ_3}}, then somehow exactly right. Grandma {{GRANDMA_NAME}} tasted it, made a {{ADJ_4}} face, and said it was \"{{ADJ_5}} — but not quite.\"",
    fields: [
      { key: "GRANDMA_NAME",  label: "Grandma's name",   hint: "e.g., Eunice" },
      { key: "DISH",          label: "Famous dish",      hint: "e.g., beef stew" },
      { key: "OCCASION",      label: "Family occasion",  hint: "e.g., holiday" },
      { key: "NUMBER_1",      label: "Years",            hint: "e.g., sixty-three" },
      { key: "ADJ_1",         label: "Adjective",        hint: "e.g., dramatic" },
      { key: "NAME_1",        label: "Relative's name",  hint: "e.g., Todd" },
      { key: "AMOUNT_1",      label: "Vague amount",     hint: "e.g., three" },
      { key: "INGREDIENT_1",  label: "Main ingredient",  hint: "e.g., onions" },
      { key: "SMELL",         label: "Smell description",hint: "e.g., a summer afternoon" },
      { key: "INGREDIENT_2",  label: "Second ingredient",hint: "e.g., paprika" },
      { key: "NOUN_1",        label: "Part of dish",     hint: "e.g., sauce" },
      { key: "VERB_1",        label: "Verb",             hint: "e.g., hum" },
      { key: "NUMBER_2",      label: "Number of attempts",hint: "e.g., four" },
      { key: "VERB_2",        label: "Past tense verb",  hint: "e.g., solidified" },
      { key: "COLOR",         label: "Alarming color",   hint: "e.g., mauve" },
      { key: "VERB_3",        label: "Past tense verb",  hint: "e.g., bubbled" },
      { key: "NUMBER_3",      label: "Successful batch", hint: "e.g., five" },
      { key: "ADJ_2",         label: "Adjective",        hint: "e.g., watery" },
      { key: "ADJ_3",         label: "Adjective",        hint: "e.g., thick" },
      { key: "ADJ_4",         label: "Adjective",        hint: "e.g., unreadable" },
      { key: "ADJ_5",         label: "Adjective",        hint: "e.g., close" },
    ]
  },

  competitive_eating: {
    title: "The Eating Competition",
    category: "Food & Cooking",
    story: "The {{NUMBER_1}}th Annual {{FOOD_1}} Eating Championship at {{VENUE}} drew {{NUMBER_2}} spectators to watch {{NAME_1}}, the {{ADJ_1}} reigning champion, defend their title. Their main rival this year was {{NAME_2}}, a {{ADJ_2}} newcomer from {{PLACE_1}} who had allegedly {{VERB_1}}ed {{NUMBER_3}} {{FOOD_1}}s in training. The referee, {{NAME_3}}, explained the rules in a {{ADJ_3}} voice: {{NUMBER_4}} minutes, as many {{FOOD_1}}s as possible, no {{VERB_2}}ing in the first thirty seconds. At the bell, {{NAME_1}} {{VERB_3}}ed at {{ADJ_4}} speed while {{NAME_2}} attempted a {{ADJ_5}} technique that the announcer described as \"{{TECHNIQUE}}.\" With three seconds remaining, {{NAME_1}} {{VERB_4}}ed ahead to claim victory, accepting the {{ADJ_6}} trophy while the crowd {{VERB_5}}ed {{ADJ_7}}ly.",
    fields: [
      { key: "NUMBER_1",   label: "Edition number",    hint: "e.g., seventeenth" },
      { key: "FOOD_1",     label: "Competition food",  hint: "e.g., hot dog" },
      { key: "VENUE",      label: "Venue name",        hint: "e.g., Blandsville Park" },
      { key: "NUMBER_2",   label: "Spectators",        hint: "e.g., four hundred" },
      { key: "NAME_1",     label: "Champion's name",   hint: "e.g., Big Munchy Dave" },
      { key: "ADJ_1",      label: "Adjective",         hint: "e.g., legendary" },
      { key: "NAME_2",     label: "Rival's name",      hint: "e.g., The Jaw" },
      { key: "ADJ_2",      label: "Adjective",         hint: "e.g., mysterious" },
      { key: "PLACE_1",    label: "Rival's hometown",  hint: "e.g., Toledo" },
      { key: "VERB_1",     label: "Past tense verb",   hint: "e.g., consumed" },
      { key: "NUMBER_3",   label: "Training amount",   hint: "e.g., eighty" },
      { key: "NAME_3",     label: "Referee's name",    hint: "e.g., Harold" },
      { key: "ADJ_3",      label: "Adjective",         hint: "e.g., nasal" },
      { key: "NUMBER_4",   label: "Minutes to eat",    hint: "e.g., ten" },
      { key: "VERB_2",     label: "Forbidden verb",    hint: "e.g., chewing" },
      { key: "VERB_3",     label: "Past tense verb",   hint: "e.g., powered through" },
      { key: "ADJ_4",      label: "Adjective",         hint: "e.g., mechanical" },
      { key: "ADJ_5",      label: "Adjective",         hint: "e.g., controversial" },
      { key: "TECHNIQUE",  label: "Named technique",   hint: "e.g., The Reverse Funnel" },
      { key: "VERB_4",     label: "Past tense verb",   hint: "e.g., surged" },
      { key: "ADJ_6",      label: "Adjective",         hint: "e.g., oversized golden" },
      { key: "VERB_5",     label: "Past tense verb",   hint: "e.g., wept" },
      { key: "ADJ_7",      label: "Adjective",         hint: "e.g., uncontrollably" },
    ]
  },

});
