window.MADLIB_TEMPLATES = window.MADLIB_TEMPLATES || {};
Object.assign(window.MADLIB_TEMPLATES, {

  haunted_house_hunt: {
    title: "The Haunted House Hunt",
    category: "Spooky & Mystery",
    story: "The real estate listing described {{ADDRESS}} as a \"{{ADJ_1}} fixer-upper with {{ADJ_2}} character.\" What it did not mention was the {{ADJ_3}} shadow that {{VERB_1}}ed across the ceiling every night at exactly {{TIME}}, the fact that the {{NOUN_1}} in the kitchen {{VERB_2}}ed in perfect {{ADJECTIVE_SOUND}} whenever someone said the word \"{{TRIGGER_WORD}},\" or that the previous {{NUMBER_1}} owners had all mysteriously developed an urge to {{VERB_3}} and move to {{PLACE}}. {{NAME_1}} moved in anyway because the price was {{ADJ_4}}. By week two, they had named the shadow \"{{GHOST_NAME}},\" built it a {{NOUN_2}}, and started leaving out {{FOOD}} as a peace offering. The house inspector's report read: \"{{ADJ_5}} foundation, good bones, {{NUMBER_2}} unidentified presences — all {{ADJ_6}}.\"",
    fields: [
      { key: "ADDRESS",       label: "House address",    hint: "e.g., 13 Willow Lane" },
      { key: "ADJ_1",         label: "Adjective",        hint: "e.g., charming" },
      { key: "ADJ_2",         label: "Adjective",        hint: "e.g., historic" },
      { key: "ADJ_3",         label: "Adjective",        hint: "e.g., flickering" },
      { key: "VERB_1",        label: "Verb (-ed)",       hint: "e.g., slithered" },
      { key: "TIME",          label: "Nightly time",     hint: "e.g., 3:17 AM" },
      { key: "NOUN_1",        label: "Kitchen item",     hint: "e.g., sink faucet" },
      { key: "VERB_2",        label: "Verb (-ed)",       hint: "e.g., howled" },
      { key: "ADJECTIVE_SOUND",label: "Sound quality",  hint: "e.g., operatic" },
      { key: "TRIGGER_WORD",  label: "Trigger word",     hint: "e.g., mortgage" },
      { key: "NUMBER_1",      label: "Previous owners",  hint: "e.g., seven" },
      { key: "VERB_3",        label: "Verb",             hint: "e.g., knit obsessively" },
      { key: "PLACE",         label: "Where they moved", hint: "e.g., Vermont" },
      { key: "NAME_1",        label: "New owner name",   hint: "e.g., Priscilla" },
      { key: "ADJ_4",         label: "Adjective",        hint: "e.g., reasonable" },
      { key: "GHOST_NAME",    label: "Ghost's name",     hint: "e.g., Druscilla" },
      { key: "NOUN_2",        label: "Thing built for ghost",hint: "e.g., little shrine" },
      { key: "FOOD",          label: "Food offering",    hint: "e.g., crackers" },
      { key: "ADJ_5",         label: "Adjective",        hint: "e.g., solid" },
      { key: "NUMBER_2",      label: "Number of presences",hint: "e.g., three" },
      { key: "ADJ_6",         label: "Adjective",        hint: "e.g., friendly" },
    ]
  },

  monster_under_bed: {
    title: "The Monster Under the Bed",
    category: "Spooky & Mystery",
    story: "{{NAME_1}} had suspected something was living under their bed ever since the {{NOUN_1}} {{VERB_1}}ed on its own at {{TIME}}. The evidence was {{ADJ_1}}: {{NUMBER_1}} missing {{NOUN_2}}s, a {{ADJ_2}} scratching sound every {{DAY_OF_WEEK}}, and the faint smell of {{SMELL}}. {{NAME_1}} attempted to investigate using a {{NOUN_3}} and a {{ADJ_3}} flashlight. What they found was not a monster but {{CREATURE_NAME}}, a {{ADJ_4}} {{NOUN_4}} who had been living there for {{NUMBER_2}} {{TIME_UNIT}}s and had organized everything under the bed into {{NUMBER_3}} very neat piles labeled {{LABEL_1}}, {{LABEL_2}}, and {{LABEL_3}}. {{CREATURE_NAME}} apologized for the smell — it had been {{VERB_2}}ing a batch of {{FOOD}} — and offered {{NAME_1}} some. It was {{ADJ_5}}.",
    fields: [
      { key: "NAME_1",     label: "Person's name",     hint: "e.g., Oliver" },
      { key: "NOUN_1",     label: "Bedroom item",      hint: "e.g., lamp" },
      { key: "VERB_1",     label: "Past tense verb",   hint: "e.g., swiveled" },
      { key: "TIME",       label: "Time it happened",  hint: "e.g., 2:43 AM" },
      { key: "ADJ_1",      label: "Adjective",         hint: "e.g., mounting" },
      { key: "NUMBER_1",   label: "Number missing",    hint: "e.g., fourteen" },
      { key: "NOUN_2",     label: "Missing items",     hint: "e.g., sock" },
      { key: "ADJ_2",      label: "Adjective",         hint: "e.g., rhythmic" },
      { key: "DAY_OF_WEEK",label: "Day of week",       hint: "e.g., Tuesday" },
      { key: "SMELL",      label: "Strange smell",     hint: "e.g., cinnamon and regret" },
      { key: "NOUN_3",     label: "Investigation tool",hint: "e.g., ruler" },
      { key: "ADJ_3",      label: "Adjective",         hint: "e.g., flickering" },
      { key: "CREATURE_NAME",label: "Creature's name", hint: "e.g., Gerald" },
      { key: "ADJ_4",      label: "Adjective",         hint: "e.g., small" },
      { key: "NOUN_4",     label: "Creature type",     hint: "e.g., dust bunny" },
      { key: "NUMBER_2",   label: "Time living there", hint: "e.g., three" },
      { key: "TIME_UNIT",  label: "Time unit",         hint: "e.g., year" },
      { key: "NUMBER_3",   label: "Number of piles",   hint: "e.g., seven" },
      { key: "LABEL_1",    label: "Pile label 1",      hint: "e.g., Urgent" },
      { key: "LABEL_2",    label: "Pile label 2",      hint: "e.g., Pending" },
      { key: "LABEL_3",    label: "Pile label 3",      hint: "e.g., Miscellaneous" },
      { key: "VERB_2",     label: "Verb (-ing)",       hint: "e.g., fermenting" },
      { key: "FOOD",       label: "Creature's food",   hint: "e.g., mushroom tea" },
      { key: "ADJ_5",      label: "Adjective",         hint: "e.g., surprisingly delicious" },
    ]
  },

  mysterious_neighbor: {
    title: "The Mysterious Neighbor",
    category: "Spooky & Mystery",
    story: "Nobody in {{NEIGHBORHOOD}} had ever seen the occupant of {{ADDRESS}}. The lights flickered {{ADJ_1}}ly at {{TIME}} each night, deliveries arrived in {{ADJ_2}} boxes labeled \"{{LABEL}},\" and a {{ADJ_3}} {{SOUND}} emerged from the {{NOUN_1}} every {{DAY_OF_WEEK}}. The neighborhood's self-appointed investigator, {{NAME_1}}, began keeping a {{ADJ_4}} log: Tuesday — {{NOTE_1}}. Thursday — {{NOTE_2}}. Friday — the {{NOUN_2}} somehow {{VERB_1}}ed itself. The mystery was solved at the HOA meeting when the neighbor arrived in person: {{NAME_2}}, a {{ADJ_5}} {{OCCUPATION}} who worked nights, received medical equipment, practiced {{INSTRUMENT}} badly, and was — in their own words — \"just {{ADJ_6}}\" about the whole investigation. They brought {{FOOD}} to the meeting. It was {{ADJ_7}}.",
    fields: [
      { key: "NEIGHBORHOOD",label: "Neighborhood name", hint: "e.g., Pinecrest Hollow" },
      { key: "ADDRESS",     label: "House address",     hint: "e.g., 42 Creeper Lane" },
      { key: "ADJ_1",       label: "Adjective",         hint: "e.g., ominously" },
      { key: "TIME",        label: "Flickering time",   hint: "e.g., midnight" },
      { key: "ADJ_2",       label: "Adjective",         hint: "e.g., unmarked" },
      { key: "LABEL",       label: "Box label",         hint: "e.g., DO NOT OPEN" },
      { key: "ADJ_3",       label: "Adjective",         hint: "e.g., low, rhythmic" },
      { key: "SOUND",       label: "Sound type",        hint: "e.g., humming" },
      { key: "NOUN_1",      label: "House location",    hint: "e.g., basement" },
      { key: "DAY_OF_WEEK", label: "Day of sound",      hint: "e.g., Wednesday" },
      { key: "NAME_1",      label: "Investigator name", hint: "e.g., Marge" },
      { key: "ADJ_4",       label: "Adjective",         hint: "e.g., meticulous" },
      { key: "NOTE_1",      label: "Log entry 1",       hint: "e.g., crows gathered" },
      { key: "NOTE_2",      label: "Log entry 2",       hint: "e.g., three packages" },
      { key: "NOUN_2",      label: "Mysterious item",   hint: "e.g., garden gnome" },
      { key: "VERB_1",      label: "Past tense verb",   hint: "e.g., rearranged" },
      { key: "NAME_2",      label: "Neighbor's name",   hint: "e.g., Derek" },
      { key: "ADJ_5",       label: "Adjective",         hint: "e.g., perfectly normal" },
      { key: "OCCUPATION",  label: "Occupation",        hint: "e.g., hospital administrator" },
      { key: "INSTRUMENT",  label: "Instrument",        hint: "e.g., didgeridoo" },
      { key: "ADJ_6",       label: "Adjective",         hint: "e.g., mortified" },
      { key: "FOOD",        label: "Food they brought", hint: "e.g., lemon bars" },
      { key: "ADJ_7",       label: "Adjective",         hint: "e.g., excellent" },
    ]
  },

  missing_sock: {
    title: "The Case of the Missing Sock",
    category: "Spooky & Mystery",
    story: "Detective {{DETECTIVE_NAME}} had cracked {{NUMBER_1}} cases, but nothing prepared them for the mystery of the missing sock on {{DATE}}. The victim — one {{ADJ_1}} {{COLOR}} sock belonging to {{CLIENT_NAME}} — had vanished between the dryer and the {{NOUN_1}}. {{DETECTIVE_NAME}} surveyed the scene: {{NUMBER_2}} {{ADJ_2}} clues, a {{NOUN_2}} placed {{ADJ_3}}ly near the vent, and a {{ADJ_4}} trail of {{NOUN_3}} leading to the {{PLACE}}. Suspects included: the {{ADJ_5}} {{APPLIANCE}}, which had a history of {{VERB_1}}ing small items; the cat, {{CAT_NAME}}, who was suspiciously {{ADJ_6}}; and the concept of entropy. After {{NUMBER_3}} hours of investigation, the sock was found {{LOCATION}}, along with {{NUMBER_4}} other socks and a {{NOUN_4}} from {{YEAR}}. Case {{ADJ_7}}.",
    fields: [
      { key: "DETECTIVE_NAME",label: "Detective name",  hint: "e.g., Sergeant Fluff" },
      { key: "NUMBER_1",      label: "Cases solved",    hint: "e.g., forty-seven" },
      { key: "DATE",          label: "Date of crime",   hint: "e.g., the 14th" },
      { key: "ADJ_1",         label: "Adjective",       hint: "e.g., beloved" },
      { key: "COLOR",         label: "Sock color",      hint: "e.g., argyle green" },
      { key: "CLIENT_NAME",   label: "Sock owner",      hint: "e.g., Harold" },
      { key: "NOUN_1",        label: "Laundry area",    hint: "e.g., folding table" },
      { key: "NUMBER_2",      label: "Number of clues", hint: "e.g., three" },
      { key: "ADJ_2",         label: "Adjective",       hint: "e.g., circumstantial" },
      { key: "NOUN_2",        label: "Suspicious item", hint: "e.g., dryer sheet" },
      { key: "ADJ_3",         label: "Adjective",       hint: "e.g., deliberately" },
      { key: "NOUN_3",        label: "Trail material",  hint: "e.g., lint" },
      { key: "PLACE",         label: "Trail destination",hint: "e.g., utility closet" },
      { key: "ADJ_5",         label: "Adjective",       hint: "e.g., industrial" },
      { key: "APPLIANCE",     label: "Appliance suspect",hint: "e.g., washing machine" },
      { key: "VERB_1",        label: "Verb (-ing)",     hint: "e.g., consuming" },
      { key: "CAT_NAME",      label: "Cat's name",      hint: "e.g., Mozzarella" },
      { key: "ADJ_6",         label: "Adjective",       hint: "e.g., calm" },
      { key: "NUMBER_3",      label: "Investigation hours",hint: "e.g., six" },
      { key: "LOCATION",      label: "Where sock was",  hint: "e.g., behind the radiator" },
      { key: "NUMBER_4",      label: "Other socks found",hint: "e.g., eleven" },
      { key: "NOUN_4",        label: "Mystery bonus item",hint: "e.g., TV remote" },
      { key: "YEAR",          label: "Year of item",    hint: "e.g., 2018" },
      { key: "ADJ_7",         label: "Case status",     hint: "e.g., closed" },
    ]
  },

  spooky_sleepover: {
    title: "The Spooky Sleepover",
    category: "Spooky & Mystery",
    story: "The sleepover at {{NAME_1}}'s house started {{ADJ_1}}ly enough — {{FOOD_1}}, {{ACTIVITY}}, and {{NUMBER_1}} {{ADJ_2}} friends in sleeping bags. Then {{NAME_2}} suggested telling {{ADJ_3}} stories. The first story — \"{{STORY_TITLE}}\" — was so {{ADJ_4}} that {{NAME_3}} {{VERB_1}}ed into their sleeping bag and didn't emerge for {{NUMBER_2}} minutes. {{NAME_4}} claimed they'd {{VERB_2}}ed something {{ADJ_5}} in the {{NOUN_1}}, which everyone agreed was probably just {{MUNDANE_EXPLANATION}}. The real scare came at {{TIME}} when the {{NOUN_2}} made a {{ADJ_6}} sound and all the {{NOUN_3}}s went out at once. {{NUMBER_3}} people {{VERB_3}}ed simultaneously. The cause: {{NAME_1}}'s {{PET_NAME}} the {{ANIMAL_TYPE}} had {{VERB_4}}ed on the power strip. {{PET_NAME}} looked {{ADJ_7}} about it. Everyone agreed it was the best sleepover ever.",
    fields: [
      { key: "NAME_1",          label: "Host's name",      hint: "e.g., Celeste" },
      { key: "ADJ_1",           label: "Adjective",        hint: "e.g., innocuously" },
      { key: "FOOD_1",          label: "Sleepover food",   hint: "e.g., pizza" },
      { key: "ACTIVITY",        label: "Activity",         hint: "e.g., board games" },
      { key: "NUMBER_1",        label: "Number of friends",hint: "e.g., five" },
      { key: "ADJ_2",           label: "Adjective",        hint: "e.g., nervous" },
      { key: "NAME_2",          label: "Story suggester",  hint: "e.g., Jordan" },
      { key: "ADJ_3",           label: "Adjective",        hint: "e.g., scary" },
      { key: "STORY_TITLE",     label: "Scary story title",hint: "e.g., The Thing in the Dryer" },
      { key: "ADJ_4",           label: "Adjective",        hint: "e.g., terrifying" },
      { key: "NAME_3",          label: "Scared person",    hint: "e.g., Sam" },
      { key: "VERB_1",          label: "Past tense verb",  hint: "e.g., dove" },
      { key: "NUMBER_2",        label: "Minutes in bag",   hint: "e.g., fifteen" },
      { key: "NAME_4",          label: "Nervous person",   hint: "e.g., Mikey" },
      { key: "VERB_2",          label: "Past tense verb",  hint: "e.g., heard" },
      { key: "ADJ_5",           label: "Adjective",        hint: "e.g., strange" },
      { key: "NOUN_1",          label: "Spooky location",  hint: "e.g., hallway" },
      { key: "MUNDANE_EXPLANATION",label: "Normal explanation",hint: "e.g., the furnace" },
      { key: "TIME",            label: "Scary time",       hint: "e.g., 1:23 AM" },
      { key: "NOUN_2",          label: "Noise source",     hint: "e.g., refrigerator" },
      { key: "ADJ_6",           label: "Adjective",        hint: "e.g., horrifying" },
      { key: "NOUN_3",          label: "Light sources",    hint: "e.g., flashlight" },
      { key: "NUMBER_3",        label: "People who screamed",hint: "e.g., all six" },
      { key: "VERB_3",          label: "Past tense verb",  hint: "e.g., screamed" },
      { key: "NAME_1_2",        label: "Host name again",  hint: "e.g., Celeste" },
      { key: "PET_NAME",        label: "Pet's name",       hint: "e.g., Noodles" },
      { key: "ANIMAL_TYPE",     label: "Type of pet",      hint: "e.g., hamster" },
      { key: "VERB_4",          label: "Past tense verb",  hint: "e.g., sat" },
      { key: "ADJ_7",           label: "Adjective",        hint: "e.g., completely unbothered" },
    ]
  },

});
