window.MADLIB_TEMPLATES = window.MADLIB_TEMPLATES || {};
Object.assign(window.MADLIB_TEMPLATES, {

  weird_school_day: {
    title: "My Weird Day at School",
    category: "School Life",
    story: "Today at {{SCHOOL_NAME}} Middle School, something truly {{ADJ_1}} happened. My teacher, {{NAME_1}}, walked in wearing a {{ADJ_2}} {{NOUN_1}} on their head and announced we'd be studying {{SUBJECT}} using only {{NOUN_2}}s. The entire class began to {{VERB_1}} uncontrollably. Then a {{ADJ_3}} {{ANIMAL}} {{VERB_2}} through the window and sat on {{NAME_2}}'s desk. By lunch, we were all {{VERB_3}} in the cafeteria eating {{ADJ_4}} {{FOOD}}. It was the most {{ADJ_5}} school day in history.",
    fields: [
      { key: "SCHOOL_NAME",label: "School name",       hint: "e.g., Westview" },
      { key: "ADJ_1",      label: "Adjective",         hint: "e.g., chaotic" },
      { key: "NAME_1",     label: "Teacher's name",    hint: "e.g., Mr. Wiggins" },
      { key: "ADJ_2",      label: "Adjective",         hint: "e.g., flaming" },
      { key: "NOUN_1",     label: "Object (worn)",     hint: "e.g., colander" },
      { key: "SUBJECT",    label: "School subject",    hint: "e.g., calculus" },
      { key: "NOUN_2",     label: "Noun",              hint: "e.g., pickle" },
      { key: "VERB_1",     label: "Verb",              hint: "e.g., howl" },
      { key: "ADJ_3",      label: "Adjective",         hint: "e.g., enormous" },
      { key: "ANIMAL",     label: "Animal",            hint: "e.g., capybara" },
      { key: "VERB_2",     label: "Past tense verb",   hint: "e.g., waddled" },
      { key: "NAME_2",     label: "Classmate's name",  hint: "e.g., Timmy" },
      { key: "VERB_3",     label: "Verb (-ing)",       hint: "e.g., yodeling" },
      { key: "ADJ_4",      label: "Adjective",         hint: "e.g., radioactive" },
      { key: "FOOD",       label: "Food",              hint: "e.g., spaghetti" },
      { key: "ADJ_5",      label: "Adjective",         hint: "e.g., unforgettable" },
    ]
  },

  science_fair: {
    title: "The Science Fair Disaster",
    category: "School Life",
    story: "For the {{SCHOOL_NAME}} Science Fair, {{NAME_1}} planned to demonstrate how {{NOUN_1}} affects the {{ADJ_1}} behavior of {{ANIMAL_PLURAL}}. The experiment required a {{ADJ_2}} container, {{NUMBER_1}} gallons of {{LIQUID}}, and exactly {{NUMBER_2}} {{NOUN_2}}s. Everything went fine until {{NAME_1}} accidentally {{VERB_1}}ed the wrong beaker and the entire mixture turned {{COLOR}} and began to {{VERB_2}}. Principal {{NAME_2}} arrived just in time to see the gym ceiling covered in {{ADJ_3}} {{NOUN_3}}. {{NAME_1}} won third place. The first-place trophy went to a {{ADJ_4}} potato that somehow learned to {{VERB_3}}.",
    fields: [
      { key: "SCHOOL_NAME",  label: "School name",      hint: "e.g., Jefferson" },
      { key: "NAME_1",       label: "Student's name",   hint: "e.g., Priya" },
      { key: "NOUN_1",       label: "Variable",         hint: "e.g., loud music" },
      { key: "ADJ_1",        label: "Adjective",        hint: "e.g., mating" },
      { key: "ANIMAL_PLURAL",label: "Animals (plural)", hint: "e.g., salamanders" },
      { key: "ADJ_2",        label: "Adjective",        hint: "e.g., pressure-sealed" },
      { key: "NUMBER_1",     label: "Number",           hint: "e.g., twelve" },
      { key: "LIQUID",       label: "Liquid",           hint: "e.g., pickle brine" },
      { key: "NUMBER_2",     label: "Number",           hint: "e.g., forty" },
      { key: "NOUN_2",       label: "Noun",             hint: "e.g., rubber duck" },
      { key: "VERB_1",       label: "Past tense verb",  hint: "e.g., sneezed on" },
      { key: "COLOR",        label: "Color",            hint: "e.g., neon orange" },
      { key: "VERB_2",       label: "Verb",             hint: "e.g., growl" },
      { key: "NAME_2",       label: "Principal's name", hint: "e.g., Principal Knob" },
      { key: "ADJ_3",        label: "Adjective",        hint: "e.g., sparkling" },
      { key: "NOUN_3",       label: "Plural noun",      hint: "e.g., anchovies" },
      { key: "ADJ_4",        label: "Adjective",        hint: "e.g., overachieving" },
      { key: "VERB_3",       label: "Verb",             hint: "e.g., recite poetry" },
    ]
  },

  field_trip: {
    title: "Field Trip Gone Wrong",
    category: "School Life",
    story: "The class field trip to {{PLACE_1}} started normally enough, until {{NAME_1}} {{VERB_1}}ed directly into a {{ADJ_1}} {{NOUN_1}} and set off a chain of events that would be {{VERB_2}}ed about for years. Within minutes, {{NUMBER}} students were {{VERB_3}}ing, the chaperone ({{NAME_2}}) was stuck inside a {{ADJ_2}} {{NOUN_2}}, and the tour guide had begun {{VERB_4}}ing in what we can only describe as {{ADJ_3}} panic. The bus driver, a {{ADJ_4}} person named {{NAME_3}}, saved the day by {{VERB_5}}ing the bus directly through the {{NOUN_3}} wall. Everyone got back safely, but the permission slips for next year mentioned nothing about {{NOUN_4}}s.",
    fields: [
      { key: "PLACE_1",  label: "Field trip location", hint: "e.g., the cheese museum" },
      { key: "NAME_1",   label: "Student's name",      hint: "e.g., Kevin" },
      { key: "VERB_1",   label: "Past tense verb",     hint: "e.g., tripped" },
      { key: "ADJ_1",    label: "Adjective",           hint: "e.g., load-bearing" },
      { key: "NOUN_1",   label: "Noun",                hint: "e.g., display case" },
      { key: "VERB_2",   label: "Passive verb",        hint: "e.g., talked" },
      { key: "NUMBER",   label: "Number",              hint: "e.g., fourteen" },
      { key: "VERB_3",   label: "Verb (-ing)",         hint: "e.g., shrieking" },
      { key: "NAME_2",   label: "Chaperone's name",    hint: "e.g., Mr. Blorp" },
      { key: "ADJ_2",    label: "Adjective",           hint: "e.g., revolving" },
      { key: "NOUN_2",   label: "Structure",           hint: "e.g., gift shop display" },
      { key: "VERB_4",   label: "Verb (-ing)",         hint: "e.g., hyperventilating" },
      { key: "ADJ_3",    label: "Adjective",           hint: "e.g., interpretive" },
      { key: "ADJ_4",    label: "Adjective",           hint: "e.g., unflappable" },
      { key: "NAME_3",   label: "Bus driver's name",   hint: "e.g., Rhonda" },
      { key: "VERB_5",   label: "Past tense verb",     hint: "e.g., reversing" },
      { key: "NOUN_3",   label: "Noun",                hint: "e.g., hedge" },
      { key: "NOUN_4",   label: "Noun",                hint: "e.g., self-guided tour" },
    ]
  },

  spelling_bee: {
    title: "The Spelling Bee Championship",
    category: "School Life",
    story: "{{NAME_1}} had trained for the {{SCHOOL_NAME}} Regional Spelling Bee for {{NUMBER_1}} months, practicing {{ADJ_1}} words for {{NUMBER_2}} hours a day. The competition was fierce, with {{NUMBER_3}} other contestants including the reigning champion, {{NAME_2}}, who reportedly {{VERB_1}}ed the dictionary as a hobby. In the final round, {{NAME_1}} faced the word \"{{MADE_UP_WORD}}.\" The crowd went {{ADJ_2}}. After {{NUMBER_4}} seconds of {{ADJ_3}} silence, {{NAME_1}} {{VERB_2}}ed confidently and spelled it letter by letter. The judge stared. The judge {{VERB_3}}ed. \"Correct,\" the judge said, in a voice that was clearly {{ADJ_4}}.",
    fields: [
      { key: "NAME_1",      label: "Contestant's name", hint: "e.g., Ophelia" },
      { key: "SCHOOL_NAME", label: "School/Region name",hint: "e.g., Tri-County" },
      { key: "NUMBER_1",    label: "Number of months",  hint: "e.g., eleven" },
      { key: "ADJ_1",       label: "Adjective",         hint: "e.g., obscure" },
      { key: "NUMBER_2",    label: "Hours per day",     hint: "e.g., seven" },
      { key: "NUMBER_3",    label: "Contestants",       hint: "e.g., forty-two" },
      { key: "NAME_2",      label: "Rival's name",      hint: "e.g., Maximilian" },
      { key: "VERB_1",      label: "Past tense verb",   hint: "e.g., devoured" },
      { key: "MADE_UP_WORD",label: "Ridiculous word",   hint: "e.g., flurpnicate" },
      { key: "ADJ_2",       label: "Adjective",         hint: "e.g., silent" },
      { key: "NUMBER_4",    label: "Number of seconds", hint: "e.g., forty-five" },
      { key: "ADJ_3",       label: "Adjective",         hint: "e.g., agonizing" },
      { key: "VERB_2",      label: "Past tense verb",   hint: "e.g., cleared their throat" },
      { key: "VERB_3",      label: "Past tense verb",   hint: "e.g., blinked" },
      { key: "ADJ_4",       label: "Adjective",         hint: "e.g., suspicious" },
    ]
  },

  school_play: {
    title: "The School Play Catastrophe",
    category: "School Life",
    story: "Opening night of {{SCHOOL_NAME}}'s production of \"{{PLAY_TITLE}}\" began with enormous {{NOUN_1}}, despite the fact that the lead actor, {{NAME_1}}, had only {{VERB_1}}ed their lines once and didn't own any {{ADJ_1}} shoes. The first act went {{ADJ_2}} until the backdrop — a {{ADJ_3}} painting of {{PLACE}} — fell directly onto the {{OCCUPATION}}. {{NAME_1}} improvised {{ADJ_4}}ly, delivering an unscripted speech about {{NOUN_2}} that brought the audience to tears. The curtain call was interrupted when the stage lights {{VERB_2}}ed, bathing everything in {{COLOR}} and playing {{SONG_TITLE}} on repeat. The review in the school paper called it \"{{ADJ_5}}\" and awarded {{NUMBER}} stars.",
    fields: [
      { key: "SCHOOL_NAME", label: "School name",       hint: "e.g., Pinecrest" },
      { key: "PLAY_TITLE",  label: "Play title",        hint: "e.g., Hamlet II: More Hamlet" },
      { key: "NOUN_1",      label: "Noun (emotion)",    hint: "e.g., dread" },
      { key: "NAME_1",      label: "Lead actor's name", hint: "e.g., Barnsworth" },
      { key: "VERB_1",      label: "Past tense verb",   hint: "e.g., skimmed" },
      { key: "ADJ_1",       label: "Adjective",         hint: "e.g., period-appropriate" },
      { key: "ADJ_2",       label: "Adjective",         hint: "e.g., adequately" },
      { key: "ADJ_3",       label: "Adjective",         hint: "e.g., ambitious" },
      { key: "PLACE",       label: "Place depicted",    hint: "e.g., ancient Rome" },
      { key: "OCCUPATION",  label: "Theater role",      hint: "e.g., stage manager" },
      { key: "ADJ_4",       label: "Adverb base",       hint: "e.g., bold" },
      { key: "NOUN_2",      label: "Topic",             hint: "e.g., cheese" },
      { key: "VERB_2",      label: "Past tense verb",   hint: "e.g., malfunctioned" },
      { key: "COLOR",       label: "Color",             hint: "e.g., magenta" },
      { key: "SONG_TITLE",  label: "Song title",        hint: "e.g., Macarena" },
      { key: "ADJ_5",       label: "Adjective",         hint: "e.g., transformative" },
      { key: "NUMBER",      label: "Star rating",       hint: "e.g., eleven" },
    ]
  },

  sub_teacher: {
    title: "The Substitute Teacher",
    category: "School Life",
    story: "When the substitute arrived — a {{ADJ_1}} person named {{NAME_1}} who claimed to have a PhD in {{SUBJECT_1}} from the University of {{MADE_UP_PLACE}} — nobody expected what was coming. {{NAME_1}} opened the class by {{VERB_1}}ing for five minutes straight, then announced the lesson would cover the {{ADJ_2}} history of {{NOUN_1}}. By second period, the class had collectively {{VERB_2}}ed their desks into a {{ADJ_3}} shape and declared themselves an independent {{NOUN_2}}. {{NAME_1}} simply {{VERB_3}}ed and awarded everyone extra credit for \"{{ADJ_4}} initiative.\" It remains the only time a class has successfully {{VERB_4}}ed a substitute into doing their homework for them.",
    fields: [
      { key: "ADJ_1",         label: "Adjective",         hint: "e.g., enthusiastic" },
      { key: "NAME_1",        label: "Sub's name",        hint: "e.g., Clarence" },
      { key: "SUBJECT_1",     label: "Subject",           hint: "e.g., interpretive cartography" },
      { key: "MADE_UP_PLACE", label: "Fake place name",   hint: "e.g., East Blorbington" },
      { key: "VERB_1",        label: "Verb (-ing)",       hint: "e.g., humming" },
      { key: "ADJ_2",         label: "Adjective",         hint: "e.g., suppressed" },
      { key: "NOUN_1",        label: "Topic",             hint: "e.g., spoon evolution" },
      { key: "VERB_2",        label: "Past tense verb",   hint: "e.g., rearranged" },
      { key: "ADJ_3",         label: "Adjective",         hint: "e.g., hexagonal" },
      { key: "NOUN_2",        label: "Type of group",     hint: "e.g., republic" },
      { key: "VERB_3",        label: "Past tense verb",   hint: "e.g., nodded" },
      { key: "ADJ_4",         label: "Adjective",         hint: "e.g., disruptive" },
      { key: "VERB_4",        label: "Past tense verb",   hint: "e.g., convinced" },
    ]
  },

  cafeteria: {
    title: "Cafeteria Chaos",
    category: "School Life",
    story: "Tuesday's lunch menu at {{SCHOOL_NAME}} listed \"{{FOOD_1}}\" but what arrived on the trays looked and smelled more like {{ADJ_1}} {{NOUN_1}}. {{NAME_1}} was the first brave soul to {{VERB_1}} it, and within seconds their face turned {{COLOR}} and they began to {{VERB_2}} the school fight song. The cafeteria erupted. {{VERB_3}} trays flew across the room like {{ADJ_2}} {{NOUN_2}}s. The lunch staff — led by the legendary {{NAME_2}} — responded by {{VERB_4}}ing an emergency batch of {{FOOD_2}}, which was {{ADJ_3}} but technically edible. Order was restored when Principal {{NAME_3}} slipped on a {{NOUN_3}} and delivered the most {{ADJ_4}} speech of their career while lying on the floor.",
    fields: [
      { key: "SCHOOL_NAME",label: "School name",       hint: "e.g., Millbrook" },
      { key: "FOOD_1",     label: "Menu item",         hint: "e.g., beef surprise" },
      { key: "ADJ_1",      label: "Adjective",         hint: "e.g., sentient" },
      { key: "NOUN_1",     label: "Gross noun",        hint: "e.g., swamp runoff" },
      { key: "NAME_1",     label: "Student's name",    hint: "e.g., Marcus" },
      { key: "VERB_1",     label: "Verb",              hint: "e.g., taste" },
      { key: "COLOR",      label: "Color",             hint: "e.g., puce" },
      { key: "VERB_2",     label: "Verb",              hint: "e.g., beatbox" },
      { key: "VERB_3",     label: "Past tense verb",   hint: "e.g., Spinning" },
      { key: "ADJ_2",      label: "Adjective",         hint: "e.g., aerodynamic" },
      { key: "NOUN_2",     label: "Plural noun",       hint: "e.g., Frisbee" },
      { key: "NAME_2",     label: "Lunch staff name",  hint: "e.g., Hortense" },
      { key: "VERB_4",     label: "Verb (-ing)",       hint: "e.g., improvising" },
      { key: "FOOD_2",     label: "Another food",      hint: "e.g., nacho cheese soup" },
      { key: "ADJ_3",      label: "Adjective",         hint: "e.g., fluorescent" },
      { key: "NAME_3",     label: "Principal's name",  hint: "e.g., Principal Dorf" },
      { key: "NOUN_3",     label: "Slippery thing",    hint: "e.g., pudding packet" },
      { key: "ADJ_4",      label: "Adjective",         hint: "e.g., motivational" },
    ]
  },

  class_pet: {
    title: "The Class Pet",
    category: "School Life",
    story: "Room {{ROOM_NUMBER}}'s new class pet — a {{ADJ_1}} {{ANIMAL}} named {{PET_NAME}} — arrived in a {{ADJ_2}} crate on a Monday morning, immediately {{VERB_1}}ing at {{NAME_1}}, who screamed so loudly that the {{NOUN_1}} in the next classroom fell off the wall. {{PET_NAME}} turned out to have {{ADJ_3}} taste: it ate only organic {{FOOD}}, refused to {{VERB_2}} unless music was playing, and once {{VERB_3}}ed its way into the principal's office and {{VERB_4}}ed his lunch. The students voted unanimously that {{PET_NAME}} should also take the upcoming {{SUBJECT}} test. It scored {{ADJ_4}}.",
    fields: [
      { key: "ROOM_NUMBER", label: "Classroom number",  hint: "e.g., 4B" },
      { key: "ADJ_1",       label: "Adjective",         hint: "e.g., allegedly calm" },
      { key: "ANIMAL",      label: "Animal",            hint: "e.g., ferret" },
      { key: "PET_NAME",    label: "Pet's name",        hint: "e.g., Destructor" },
      { key: "ADJ_2",       label: "Adjective",         hint: "e.g., reinforced" },
      { key: "VERB_1",      label: "Verb (-ing)",       hint: "e.g., hissing" },
      { key: "NAME_1",      label: "Student's name",    hint: "e.g., Tyler" },
      { key: "NOUN_1",      label: "Wall item",         hint: "e.g., periodic table" },
      { key: "ADJ_3",       label: "Adjective",         hint: "e.g., refined" },
      { key: "FOOD",        label: "Specific food",     hint: "e.g., arugula" },
      { key: "VERB_2",      label: "Verb",              hint: "e.g., exercise" },
      { key: "VERB_3",      label: "Past tense verb",   hint: "e.g., tunneled" },
      { key: "VERB_4",      label: "Past tense verb",   hint: "e.g., reorganized" },
      { key: "SUBJECT",     label: "School subject",    hint: "e.g., algebra" },
      { key: "ADJ_4",       label: "Adjective",         hint: "e.g., better than average" },
    ]
  },

  talent_show: {
    title: "The School Talent Show",
    category: "School Life",
    story: "The annual {{SCHOOL_NAME}} Talent Show had always been {{ADJ_1}}, but this year it reached a new level when {{NAME_1}} performed their original act: \"{{ACT_NAME}}.\" The routine involved a {{ADJ_2}} {{NOUN_1}}, {{NUMBER}} {{ANIMAL_PLURAL}}, and an inexplicable amount of {{NOUN_2}}. The audience sat in {{ADJ_3}} silence for the first {{NUMBER_2}} seconds, then erupted into {{NOUN_3}} as {{NAME_1}} {{VERB_1}}ed across the stage in a {{ADJ_4}} costume. The judges — {{NAME_2}}, {{NAME_3}}, and an actual {{OCCUPATION}} — deliberated for {{NUMBER_3}} minutes and awarded {{NAME_1}} the {{ADJ_5}} Trophy, plus a gift card to {{STORE_NAME}}.",
    fields: [
      { key: "SCHOOL_NAME",  label: "School name",       hint: "e.g., Oakdale" },
      { key: "ADJ_1",        label: "Adjective",         hint: "e.g., chaotic" },
      { key: "NAME_1",       label: "Performer's name",  hint: "e.g., Gwendolyn" },
      { key: "ACT_NAME",     label: "Act title",         hint: "e.g., The Cheese Whisperer" },
      { key: "ADJ_2",        label: "Adjective",         hint: "e.g., motorized" },
      { key: "NOUN_1",       label: "Prop",              hint: "e.g., hula hoop" },
      { key: "NUMBER",       label: "Number",            hint: "e.g., seventeen" },
      { key: "ANIMAL_PLURAL",label: "Animals (plural)",  hint: "e.g., guinea pigs" },
      { key: "NOUN_2",       label: "Substance",         hint: "e.g., confetti" },
      { key: "ADJ_3",        label: "Adjective",         hint: "e.g., horrified" },
      { key: "NUMBER_2",     label: "Seconds",           hint: "e.g., eleven" },
      { key: "NOUN_3",       label: "Reaction noun",     hint: "e.g., applause" },
      { key: "VERB_1",       label: "Past tense verb",   hint: "e.g., moonwalked" },
      { key: "ADJ_4",        label: "Adjective",         hint: "e.g., sequined" },
      { key: "NAME_2",       label: "Judge 1",           hint: "e.g., Ms. Patterson" },
      { key: "NAME_3",       label: "Judge 2",           hint: "e.g., Coach Brent" },
      { key: "OCCUPATION",   label: "Surprise judge",    hint: "e.g., accountant" },
      { key: "NUMBER_3",     label: "Minutes",           hint: "e.g., forty" },
      { key: "ADJ_5",        label: "Adjective",         hint: "e.g., Golden" },
      { key: "STORE_NAME",   label: "Store name",        hint: "e.g., Office Depot" },
    ]
  },

  gym_class: {
    title: "Gym Class Hero",
    category: "School Life",
    story: "Coach {{NAME_1}} blew the whistle and announced today's gym activity: \"{{SPORT_NAME}}.\" Nobody had heard of it. According to {{NAME_1}}, the rules involved {{VERB_1}}ing a {{ADJ_1}} {{NOUN_1}} over a {{ADJ_2}} net while {{VERB_2}}ing on one foot. Teams were {{ADJ_3}}: the {{COLOR_1}} Furies vs the {{COLOR_2}} {{NOUN_2}}s. {{NAME_2}} immediately proved to be suspiciously {{ADJ_4}} at the sport, prompting accusations of having {{VERB_3}}ed at home. The final score was {{SCORE_1}} to {{SCORE_2}}, and Coach {{NAME_1}} awarded the {{ADJ_5}} ribbon to {{NAME_3}}, who had spent the entire class {{VERB_4}}ing in the corner but showed great \"{{NOUN_3}}.\"",
    fields: [
      { key: "NAME_1",   label: "Coach's name",      hint: "e.g., Coach Blister" },
      { key: "SPORT_NAME",label: "Made-up sport",    hint: "e.g., Octaball" },
      { key: "VERB_1",   label: "Verb (-ing)",       hint: "e.g., hurling" },
      { key: "ADJ_1",    label: "Adjective",         hint: "e.g., lumpy" },
      { key: "NOUN_1",   label: "Ball-like object",  hint: "e.g., beanbag" },
      { key: "ADJ_2",    label: "Adjective",         hint: "e.g., rotating" },
      { key: "VERB_2",   label: "Verb (-ing)",       hint: "e.g., hopping" },
      { key: "ADJ_3",    label: "Adjective",         hint: "e.g., uneven" },
      { key: "COLOR_1",  label: "Color",             hint: "e.g., chartreuse" },
      { key: "COLOR_2",  label: "Color",             hint: "e.g., beige" },
      { key: "NOUN_2",   label: "Team mascot",       hint: "e.g., Blobfish" },
      { key: "NAME_2",   label: "Athletic student",  hint: "e.g., Dex" },
      { key: "ADJ_4",    label: "Adjective",         hint: "e.g., professional" },
      { key: "VERB_3",   label: "Past tense verb",   hint: "e.g., practiced" },
      { key: "SCORE_1",  label: "Score 1",           hint: "e.g., 47" },
      { key: "SCORE_2",  label: "Score 2",           hint: "e.g., 3" },
      { key: "ADJ_5",    label: "Adjective",         hint: "e.g., Participation" },
      { key: "NAME_3",   label: "Recipient's name",  hint: "e.g., Millicent" },
      { key: "VERB_4",   label: "Verb (-ing)",       hint: "e.g., napping" },
      { key: "NOUN_3",   label: "Abstract quality",  hint: "e.g., vibes" },
    ]
  },

});
