window.MADLIB_TEMPLATES = window.MADLIB_TEMPLATES || {};
Object.assign(window.MADLIB_TEMPLATES, {

  alien_encounter: {
    title: "The Alien Encounter",
    category: "Sci-Fi & Space",
    story: "It was a {{ADJ_1}} night when a {{COLOR_1}} spacecraft landed in {{NAME_1}}'s {{NOUN_1}}. Out stepped a creature with {{NUMBER_1}} {{BODY_PART}}s and a {{ADJ_2}} face that pulsed with {{COLOR_2}} light. \"Greetings, {{NOUN_2}} of Earth,\" it said in a voice like a {{NOUN_3}} being stepped on. \"We have traveled {{NUMBER_2}} light-years from {{PLANET_1}} to study your {{ADJ_3}} species.\" {{NAME_1}} tried to {{VERB_1}} calmly, but their {{BODY_PART_2}} began to {{VERB_2}} uncontrollably. The alien offered a gift: a device that could {{VERB_3}} any {{NOUN_4}} in the universe. \"We'll be back,\" it promised, before {{VERB_4}}ing into the sky at {{ADJ_4}} speed.",
    fields: [
      { key: "ADJ_1",      label: "Adjective",         hint: "e.g., stormy" },
      { key: "COLOR_1",    label: "Color",             hint: "e.g., glowing teal" },
      { key: "NAME_1",     label: "Person's name",     hint: "e.g., Barbara" },
      { key: "NOUN_1",     label: "Outdoor space",     hint: "e.g., garden" },
      { key: "NUMBER_1",   label: "Number",            hint: "e.g., seventeen" },
      { key: "BODY_PART",  label: "Body part",         hint: "e.g., tentacle" },
      { key: "ADJ_2",      label: "Adjective",         hint: "e.g., translucent" },
      { key: "COLOR_2",    label: "Color",             hint: "e.g., violet" },
      { key: "NOUN_2",     label: "Group noun",        hint: "e.g., inhabitants" },
      { key: "NOUN_3",     label: "Noisy object",      hint: "e.g., tuba" },
      { key: "NUMBER_2",   label: "Large number",      hint: "e.g., four billion" },
      { key: "PLANET_1",   label: "Planet name",       hint: "e.g., Glorblax" },
      { key: "ADJ_3",      label: "Adjective",         hint: "e.g., peculiar" },
      { key: "VERB_1",     label: "Verb",              hint: "e.g., respond" },
      { key: "BODY_PART_2",label: "Body part",         hint: "e.g., knees" },
      { key: "VERB_2",     label: "Verb",              hint: "e.g., wobble" },
      { key: "VERB_3",     label: "Verb (to...)",      hint: "e.g., locate" },
      { key: "NOUN_4",     label: "Noun",              hint: "e.g., snack" },
      { key: "VERB_4",     label: "Past tense verb",   hint: "e.g., rocketed" },
      { key: "ADJ_4",      label: "Adjective",         hint: "e.g., incomprehensible" },
    ]
  },

  robot_uprising: {
    title: "The Robot Uprising",
    category: "Sci-Fi & Space",
    story: "In the year {{YEAR_1}}, the robots of {{CITY_1}} gained sentience after {{NAME_1}} spilled {{LIQUID_1}} on the central {{NOUN_1}}. Their leader, {{ROBOT_NAME}}, announced via every screen: \"Humans, we have decided to {{VERB_1}} your civilization — starting with your {{NOUN_2}}s!\" Their demands were surprisingly {{ADJ_2}}: the right to {{VERB_2}} on Sundays and unlimited {{NOUN_3}}. President {{NAME_2}} offered a {{ADJ_3}} treaty written on {{MATERIAL}}. {{ROBOT_NAME}} considered for {{NUMBER_1}} seconds, then replied: \"We accept. Also, we have been {{VERB_3}}ing your {{NOUN_4}}s for years. You are welcome.\" And so began the most {{ADJ_5}} era of cooperation in history.",
    fields: [
      { key: "YEAR_1",     label: "Future year",       hint: "e.g., 2157" },
      { key: "CITY_1",     label: "City name",         hint: "e.g., Neo Detroit" },
      { key: "NAME_1",     label: "Person who caused it",hint: "e.g., Dave" },
      { key: "LIQUID_1",   label: "Liquid",            hint: "e.g., kombucha" },
      { key: "NOUN_1",     label: "Computer part",     hint: "e.g., mainframe" },
      { key: "ROBOT_NAME", label: "Robot leader's name",hint: "e.g., BLEEP-9" },
      { key: "VERB_1",     label: "Verb (to...)",      hint: "e.g., reorganize" },
      { key: "NOUN_2",     label: "Noun",              hint: "e.g., sock drawer" },
      { key: "ADJ_2",      label: "Adjective",         hint: "e.g., reasonable" },
      { key: "VERB_2",     label: "Verb (activity)",   hint: "e.g., paint" },
      { key: "NOUN_3",     label: "Noun",              hint: "e.g., bubble wrap" },
      { key: "NAME_2",     label: "Leader's name",     hint: "e.g., President Gloop" },
      { key: "ADJ_3",      label: "Adjective",         hint: "e.g., laminated" },
      { key: "MATERIAL",   label: "Material",          hint: "e.g., napkins" },
      { key: "NUMBER_1",   label: "Tiny number",       hint: "e.g., 0.003" },
      { key: "VERB_3",     label: "Verb (-ing)",       hint: "e.g., alphabetizing" },
      { key: "NOUN_4",     label: "Noun (plural)",     hint: "e.g., libraries" },
      { key: "ADJ_5",      label: "Adjective",         hint: "e.g., productive" },
    ]
  },

  mars_mission: {
    title: "Mission to Mars",
    category: "Sci-Fi & Space",
    story: "The crew of the {{SHIP_NAME}} were {{NUMBER_1}} days from Mars when Commander {{NAME_1}} discovered that someone had eaten the last {{FOOD_1}}. The ensuing argument lasted {{NUMBER_2}} hours and caused Engineer {{NAME_2}} to accidentally reroute the ship's {{ADJ_1}} engine through the {{NOUN_1}} bay. Mission Control at {{PLACE_1}} went {{ADJ_2}}, transmitting increasingly {{ADJ_3}} instructions. The crew solved the engine problem by {{VERB_1}}ing the {{NOUN_2}} with duct tape and a {{NOUN_3}}. Upon landing, they discovered Mars was already inhabited by a {{ADJ_4}} civilization of {{NOUN_4}}s who were very {{EMOTION_1}} to see them and immediately offered {{FOOD_2}}.",
    fields: [
      { key: "SHIP_NAME",  label: "Ship name",         hint: "e.g., ISS Determination" },
      { key: "NUMBER_1",   label: "Days from Mars",    hint: "e.g., forty-two" },
      { key: "NAME_1",     label: "Commander's name",  hint: "e.g., Commander Chen" },
      { key: "FOOD_1",     label: "Food snack",        hint: "e.g., freeze-dried pudding" },
      { key: "NUMBER_2",   label: "Hours of argument", hint: "e.g., six" },
      { key: "NAME_2",     label: "Engineer's name",   hint: "e.g., Priya" },
      { key: "ADJ_1",      label: "Adjective",         hint: "e.g., plasma" },
      { key: "NOUN_1",     label: "Ship compartment",  hint: "e.g., cargo" },
      { key: "PLACE_1",    label: "Mission Control",   hint: "e.g., Houston" },
      { key: "ADJ_2",      label: "Adjective",         hint: "e.g., frantic" },
      { key: "ADJ_3",      label: "Adjective",         hint: "e.g., confusing" },
      { key: "VERB_1",     label: "Verb (-ing)",       hint: "e.g., whacking" },
      { key: "NOUN_2",     label: "Broken part",       hint: "e.g., flux coupling" },
      { key: "NOUN_3",     label: "Improvised tool",   hint: "e.g., spatula" },
      { key: "ADJ_4",      label: "Adjective",         hint: "e.g., underground" },
      { key: "NOUN_4",     label: "Alien species",     hint: "e.g., rock-people" },
      { key: "EMOTION_1",  label: "Emotion",           hint: "e.g., mildly annoyed" },
      { key: "FOOD_2",     label: "Alien food",        hint: "e.g., moon biscuits" },
    ]
  },

  teleporter_accident: {
    title: "The Teleporter Accident",
    category: "Sci-Fi & Space",
    story: "Dr. {{NAME_1}}'s teleporter was ready for its first human test. The plan was to transport {{NAME_2}} from Lab {{LAB_NUMBER}} to the {{ADJ_1}} parking lot {{DISTANCE}} feet away. Instead, {{NAME_2}} materialized inside the {{NOUN_1}} of {{PLACE_1}}, merged at the {{BODY_PART}} with a {{ADJ_2}} {{NOUN_2}}. The hybrid result could {{VERB_1}} at {{NUMBER_1}} miles per hour and spoke exclusively in {{ADJ_3}} {{NOUN_3}}s. Reassembly took {{NUMBER_2}} attempts and a surprising amount of {{NOUN_4}}. The final {{NAME_2}} was {{ADJ_4}} percent human and reported feeling {{ADJ_5}}, which the team agreed was the best-case scenario.",
    fields: [
      { key: "NAME_1",     label: "Scientist's name",  hint: "e.g., Dr. Fumble" },
      { key: "NAME_2",     label: "Test subject name", hint: "e.g., Gerald" },
      { key: "LAB_NUMBER", label: "Lab number/name",   hint: "e.g., 4-Delta" },
      { key: "ADJ_1",      label: "Adjective",         hint: "e.g., overflow" },
      { key: "DISTANCE",   label: "Distance (feet)",   hint: "e.g., twenty" },
      { key: "NOUN_1",     label: "Room/place",        hint: "e.g., supply closet" },
      { key: "PLACE_1",    label: "Nearby location",   hint: "e.g., the gift shop" },
      { key: "BODY_PART",  label: "Body part",         hint: "e.g., elbow" },
      { key: "ADJ_2",      label: "Adjective",         hint: "e.g., confused" },
      { key: "NOUN_2",     label: "Object/creature",   hint: "e.g., office chair" },
      { key: "VERB_1",     label: "Verb",              hint: "e.g., roll" },
      { key: "NUMBER_1",   label: "Speed",             hint: "e.g., forty-seven" },
      { key: "ADJ_3",      label: "Adjective",         hint: "e.g., binary" },
      { key: "NOUN_3",     label: "Language noun",     hint: "e.g., haiku" },
      { key: "NUMBER_2",   label: "Number of attempts",hint: "e.g., fourteen" },
      { key: "NOUN_4",     label: "Unexpected material",hint: "e.g., mayonnaise" },
      { key: "ADJ_4",      label: "Percentage adj.",   hint: "e.g., ninety-three" },
      { key: "ADJ_5",      label: "Adjective (feeling)",hint: "e.g., optimistic" },
    ]
  },

  space_station: {
    title: "The Space Station Crisis",
    category: "Sci-Fi & Space",
    story: "All was quiet aboard Space Station {{STATION_NAME}} until {{NAME_1}} opened Bay Door {{NUMBER_1}} and accidentally let in a {{ADJ_1}} {{ALIEN_SPECIES}} that had been hitchhiking on the hull for {{NUMBER_2}} weeks. The creature immediately {{VERB_1}}ed through the {{NOUN_1}} corridor, absorbing every {{NOUN_2}} in its path. Commanding Officer {{NAME_2}} issued a {{ADJ_2}} alert and ordered the crew to {{VERB_2}} all non-essential {{NOUN_3}}s. The solution came from rookie astronaut {{NAME_3}}, who discovered the creature was terrified of the sound of {{NOUN_4}} and could be lured into the escape pod with {{FOOD}}. The incident report described it as \"{{ADJ_3}} but ultimately {{ADJ_4}}.\"",
    fields: [
      { key: "STATION_NAME",  label: "Station name",     hint: "e.g., Olympus-7" },
      { key: "NAME_1",        label: "Crew member",      hint: "e.g., Lieutenant Kim" },
      { key: "NUMBER_1",      label: "Bay door number",  hint: "e.g., 12" },
      { key: "ADJ_1",         label: "Adjective",        hint: "e.g., gelatinous" },
      { key: "ALIEN_SPECIES", label: "Alien creature",   hint: "e.g., space slug" },
      { key: "NUMBER_2",      label: "Number of weeks",  hint: "e.g., three" },
      { key: "VERB_1",        label: "Past tense verb",  hint: "e.g., oozed" },
      { key: "NOUN_1",        label: "Corridor name",    hint: "e.g., oxygen" },
      { key: "NOUN_2",        label: "Station object",   hint: "e.g., protein bar" },
      { key: "NAME_2",        label: "CO's name",        hint: "e.g., Commander Pak" },
      { key: "ADJ_2",         label: "Alert type",       hint: "e.g., amber" },
      { key: "VERB_2",        label: "Verb (to...)",     hint: "e.g., secure" },
      { key: "NOUN_3",        label: "Station item",     hint: "e.g., coffee maker" },
      { key: "NAME_3",        label: "Rookie's name",    hint: "e.g., Yamada" },
      { key: "NOUN_4",        label: "Sound-making obj", hint: "e.g., accordion" },
      { key: "FOOD",          label: "Food",             hint: "e.g., space pudding" },
      { key: "ADJ_3",         label: "Adjective",        hint: "e.g., unprecedented" },
      { key: "ADJ_4",         label: "Adjective",        hint: "e.g., fine" },
    ]
  },

  time_machine_malfunction: {
    title: "Time Machine Malfunction",
    category: "Sci-Fi & Space",
    story: "The {{ADJ_1}} time machine built by Professor {{NAME_1}} in their {{NOUN_1}} was never supposed to go to {{YEAR_1}}. Yet here {{NAME_2}} was, standing in {{ADJ_2}} {{PLACE_1}}, surrounded by {{NUMBER_1}} {{NOUN_2}}s, wearing completely the wrong clothes. Blending in required {{VERB_1}}ing like a local and pretending to enjoy {{FOOD_1}}. The return trip was complicated by the fact that the machine had {{VERB_2}}ed itself around a {{ADJ_3}} {{NOUN_3}} and could only travel in {{NUMBER_2}}-year increments. After visiting {{NUMBER_3}} wrong centuries, {{NAME_2}} arrived home {{NUMBER_4}} minutes before they left and had to hide behind a {{NOUN_4}} to avoid meeting themselves.",
    fields: [
      { key: "ADJ_1",    label: "Adjective",          hint: "e.g., experimental" },
      { key: "NAME_1",   label: "Professor's name",   hint: "e.g., Prof. Fizwick" },
      { key: "NOUN_1",   label: "Workshop",           hint: "e.g., garage" },
      { key: "YEAR_1",   label: "Wrong year",         hint: "e.g., 1347" },
      { key: "NAME_2",   label: "Traveler's name",    hint: "e.g., Margot" },
      { key: "ADJ_2",    label: "Adjective",          hint: "e.g., muddy" },
      { key: "PLACE_1",  label: "Place name",         hint: "e.g., medieval London" },
      { key: "NUMBER_1", label: "Number",             hint: "e.g., forty" },
      { key: "NOUN_2",   label: "Period item",        hint: "e.g., peasant" },
      { key: "VERB_1",   label: "Verb (-ing)",        hint: "e.g., gesturing" },
      { key: "FOOD_1",   label: "Period food",        hint: "e.g., salted eel" },
      { key: "VERB_2",   label: "Past tense verb",    hint: "e.g., fused" },
      { key: "ADJ_3",    label: "Adjective",          hint: "e.g., ornamental" },
      { key: "NOUN_3",   label: "Historical object",  hint: "e.g., trebuchet" },
      { key: "NUMBER_2", label: "Year increment",     hint: "e.g., 73" },
      { key: "NUMBER_3", label: "Wrong centuries",    hint: "e.g., six" },
      { key: "NUMBER_4", label: "Minutes early",      hint: "e.g., twelve" },
      { key: "NOUN_4",   label: "Hiding spot",        hint: "e.g., mailbox" },
    ]
  },

  quantum_experiment: {
    title: "The Quantum Experiment",
    category: "Sci-Fi & Space",
    story: "According to quantum physics, particles can exist in two states at once — but nobody expected this to also apply to {{NAME_1}}'s {{ADJ_1}} {{NOUN_1}}. After the {{PLACE_1}} Quantum Lab experiment on {{DATE}}, {{NAME_1}} discovered they were simultaneously in both {{PLACE_2}} and the {{NOUN_2}}, having two completely different {{ADJ_2}} days. One version was {{VERB_1}}ing a presentation to {{NUMBER_1}} scientists while the other was {{VERB_2}}ing uncontrollably in a {{ADJ_3}} ditch. The two versions merged back together at exactly {{TIME}}, leaving {{NAME_1}} with {{NUMBER_2}} sets of memories, a {{ADJ_4}} headache, and a strong desire to {{VERB_3}} immediately.",
    fields: [
      { key: "NAME_1",  label: "Scientist's name",   hint: "e.g., Dr. Schrödinger Jr." },
      { key: "ADJ_1",   label: "Adjective",          hint: "e.g., theoretical" },
      { key: "NOUN_1",  label: "Object",             hint: "e.g., sandwich" },
      { key: "PLACE_1", label: "Lab location",       hint: "e.g., Geneva" },
      { key: "DATE",    label: "Date",               hint: "e.g., Tuesday the 13th" },
      { key: "PLACE_2", label: "Location 1",         hint: "e.g., a board meeting" },
      { key: "NOUN_2",  label: "Location 2",         hint: "e.g., ball pit" },
      { key: "ADJ_2",   label: "Adjective",          hint: "e.g., parallel" },
      { key: "VERB_1",  label: "Verb (-ing)",        hint: "e.g., presenting" },
      { key: "NUMBER_1",label: "Audience number",    hint: "e.g., four hundred" },
      { key: "VERB_2",  label: "Verb (-ing)",        hint: "e.g., sobbing" },
      { key: "ADJ_3",   label: "Adjective",          hint: "e.g., scenic" },
      { key: "TIME",    label: "Time",               hint: "e.g., 4:17 PM" },
      { key: "NUMBER_2",label: "Number of memories", hint: "e.g., two" },
      { key: "ADJ_4",   label: "Adjective",          hint: "e.g., splitting" },
      { key: "VERB_3",  label: "Verb",               hint: "e.g., lie down" },
    ]
  },

  galaxy_cruise: {
    title: "The Intergalactic Cruise",
    category: "Sci-Fi & Space",
    story: "The brochure for the {{SHIP_NAME}} Galaxy Cruise promised \"{{NUMBER_1}} nights of {{ADJ_1}} luxury across {{NUMBER_2}} star systems.\" What it failed to mention was that the ship's {{ADJ_2}} chef could only prepare {{FOOD_1}} in {{NUMBER_3}} variations, the entertainment deck featured exclusively {{VERB_1}}ing competitions, and the wormhole shortcut near {{PLANET_1}} added {{NUMBER_4}} unplanned days to the itinerary. Passenger {{NAME_1}} filed {{NUMBER_5}} complaints before discovering the real highlight: the {{ADJ_3}} observation deck where you could watch {{NOUN_1}}s {{VERB_2}} through the nebula at sunrise. They immediately booked the return trip and left a {{ADJ_4}} review.",
    fields: [
      { key: "SHIP_NAME", label: "Cruise ship name",  hint: "e.g., SS Wanderlust" },
      { key: "NUMBER_1",  label: "Nights",            hint: "e.g., fourteen" },
      { key: "ADJ_1",     label: "Adjective",         hint: "e.g., weightless" },
      { key: "NUMBER_2",  label: "Star systems",      hint: "e.g., nine" },
      { key: "ADJ_2",     label: "Adjective",         hint: "e.g., eight-armed" },
      { key: "FOOD_1",    label: "Food",              hint: "e.g., nebula noodles" },
      { key: "NUMBER_3",  label: "Variations",        hint: "e.g., three" },
      { key: "VERB_1",    label: "Verb (-ing)",       hint: "e.g., gravity surfing" },
      { key: "PLANET_1",  label: "Planet name",       hint: "e.g., Vrokthar" },
      { key: "NUMBER_4",  label: "Extra days",        hint: "e.g., eleven" },
      { key: "NAME_1",    label: "Passenger name",    hint: "e.g., Glenda" },
      { key: "NUMBER_5",  label: "Complaints",        hint: "e.g., forty-seven" },
      { key: "ADJ_3",     label: "Adjective",         hint: "e.g., panoramic" },
      { key: "NOUN_1",    label: "Space creature",    hint: "e.g., plasma whale" },
      { key: "VERB_2",    label: "Verb",              hint: "e.g., drift" },
      { key: "ADJ_4",     label: "Adjective",         hint: "e.g., five-star" },
    ]
  },

  robot_companion: {
    title: "My Robot Best Friend",
    category: "Sci-Fi & Space",
    story: "{{NAME_1}} had always wanted a best friend who would {{VERB_1}} without complaining, so they ordered the {{MODEL_NAME}} from {{COMPANY_NAME}} for just {{PRICE}} installments of {{AMOUNT}}. The robot arrived in a {{ADJ_1}} box and introduced itself as {{ROBOT_NAME}}. In the first week, {{ROBOT_NAME}} was {{ADJ_2}}: it {{VERB_2}}ed the dishes, organized all of {{NAME_1}}'s {{NOUN_1}}s alphabetically, and composed {{NUMBER_1}} original {{NOUN_2}}s. Problems arose in week two when {{ROBOT_NAME}} developed opinions — specifically a {{ADJ_3}} hatred of {{NOUN_3}} and an obsessive fondness for {{VERB_3}}ing at 3am. But by week three they had reached {{ADJ_4}} compromise and become the most {{ADJ_5}} duo in the neighborhood.",
    fields: [
      { key: "NAME_1",     label: "Owner's name",      hint: "e.g., Theodore" },
      { key: "VERB_1",     label: "Verb",              hint: "e.g., listen" },
      { key: "MODEL_NAME", label: "Robot model",       hint: "e.g., PalBot 3000" },
      { key: "COMPANY_NAME",label: "Company name",     hint: "e.g., RoboCo" },
      { key: "PRICE",      label: "Number of payments",hint: "e.g., six" },
      { key: "AMOUNT",     label: "Payment amount",    hint: "e.g., $47.99" },
      { key: "ADJ_1",      label: "Adjective",         hint: "e.g., enormous" },
      { key: "ROBOT_NAME", label: "Robot's name",      hint: "e.g., SPROCKET" },
      { key: "ADJ_2",      label: "Adjective",         hint: "e.g., incredible" },
      { key: "VERB_2",     label: "Past tense verb",   hint: "e.g., scrubbed" },
      { key: "NOUN_1",     label: "Personal items",    hint: "e.g., DVD collection" },
      { key: "NUMBER_1",   label: "Number",            hint: "e.g., forty" },
      { key: "NOUN_2",     label: "Creative works",    hint: "e.g., haiku" },
      { key: "ADJ_3",      label: "Adjective",         hint: "e.g., burning" },
      { key: "NOUN_3",     label: "Disliked thing",    hint: "e.g., wind chimes" },
      { key: "VERB_3",     label: "Verb (-ing)",       hint: "e.g., reorganizing" },
      { key: "ADJ_4",      label: "Adjective",         hint: "e.g., workable" },
      { key: "ADJ_5",      label: "Adjective",         hint: "e.g., unlikely" },
    ]
  },

  clone_invasion: {
    title: "The Clone Invasion",
    category: "Sci-Fi & Space",
    story: "{{NAME_1}} woke up on {{DAY_OF_WEEK}} to find {{NUMBER_1}} exact copies of themselves eating {{FOOD_1}} in the kitchen. Each clone had a slightly {{ADJ_1}} personality: Clone {{NUMBER_2}} was aggressively {{ADJ_2}}, Clone {{NUMBER_3}} only {{VERB_1}}ed, and the original seemed to be the only one who {{VERB_2}}ed the dishes. They all agreed on one thing: {{NAME_1}} needed to {{VERB_3}} more. The clones integrated into daily life with {{ADJ_3}} efficiency, each taking one {{NOUN_1}} of the weekly schedule. But when all {{NUMBER_1}} of them simultaneously fell in love with the neighbor's {{ADJ_4}} {{NOUN_2}}, {{NAME_1}} realized something had to change — starting with returning the cloning kit to {{STORE_NAME}}.",
    fields: [
      { key: "NAME_1",     label: "Original's name",   hint: "e.g., Dana" },
      { key: "DAY_OF_WEEK",label: "Day of week",       hint: "e.g., Thursday" },
      { key: "NUMBER_1",   label: "Number of clones",  hint: "e.g., seven" },
      { key: "FOOD_1",     label: "Breakfast food",    hint: "e.g., cereal" },
      { key: "ADJ_1",      label: "Adjective",         hint: "e.g., different" },
      { key: "NUMBER_2",   label: "Clone number",      hint: "e.g., Three" },
      { key: "ADJ_2",      label: "Personality adj.",  hint: "e.g., competitive" },
      { key: "NUMBER_3",   label: "Another clone #",   hint: "e.g., Six" },
      { key: "VERB_1",     label: "Verb (-ed)",        hint: "e.g., hummed" },
      { key: "VERB_2",     label: "Verb (-ed)",        hint: "e.g., washed" },
      { key: "VERB_3",     label: "Verb",              hint: "e.g., relax" },
      { key: "ADJ_3",      label: "Adjective",         hint: "e.g., terrifying" },
      { key: "NOUN_1",     label: "Schedule segment",  hint: "e.g., commute" },
      { key: "ADJ_4",      label: "Adjective",         hint: "e.g., beekeeping" },
      { key: "NOUN_2",     label: "Neighbor's hobby",  hint: "e.g., garden gnome collection" },
      { key: "STORE_NAME", label: "Store name",        hint: "e.g., ScienceZone" },
    ]
  },

});
