window.MADLIB_TEMPLATES = window.MADLIB_TEMPLATES || {};
Object.assign(window.MADLIB_TEMPLATES, {

  sports_commentary: {
    title: "Live Sports Commentary",
    category: "Sports & Games",
    story: "Welcome to the {{NUMBER_1}}th Annual {{TOURNAMENT_NAME}}, and what a {{ADJ_1}} day for {{SPORT}}! I'm your announcer {{ANNOUNCER_1}}, joined by color commentator {{ANNOUNCER_2}}, who is already {{VERB_1}}ing at his notes. In today's final, {{TEAM_1}} — who haven't {{VERB_2}}ed since {{YEAR_1}} — face {{TEAM_2}}, led by the {{ADJ_2}} {{PLAYER_NAME}}, who reportedly {{VERB_3}}ed {{NUMBER_2}} {{FOOD}}s before the game as part of their \"{{RITUAL_NAME}}\" ritual. The tension is {{ADJ_3}}. The crowd of {{NUMBER_3}} {{ADJ_4}} fans is {{VERB_4}}ing. AND {{PLAYER_NAME}} {{VERB_5}}es! Incredible! {{ANNOUNCER_2}} appears to be {{VERB_6}}ing — yes, he's {{VERB_6}}ing. I've never seen {{NUMBER_4}} minutes of overtime go so {{ADJ_5}}. The final score: {{SCORE_1}} to {{SCORE_2}}, a result nobody could have {{VERB_7}}ed.",
    fields: [
      { key: "NUMBER_1",    label: "Tournament edition",hint: "e.g., thirty-seventh" },
      { key: "TOURNAMENT_NAME",label: "Tournament name",hint: "e.g., Grand Championship" },
      { key: "ADJ_1",       label: "Adjective",        hint: "e.g., historic" },
      { key: "SPORT",       label: "Sport name",       hint: "e.g., competitive chair spinning" },
      { key: "ANNOUNCER_1", label: "Announcer 1 name", hint: "e.g., Phil Shouter" },
      { key: "ANNOUNCER_2", label: "Announcer 2 name", hint: "e.g., Doug Mumbles" },
      { key: "VERB_1",      label: "Verb (-ing)",      hint: "e.g., squinting" },
      { key: "TEAM_1",      label: "Team 1 name",      hint: "e.g., the Soggy Mittens" },
      { key: "VERB_2",      label: "Past tense verb",  hint: "e.g., won" },
      { key: "YEAR_1",      label: "Year",             hint: "e.g., 1987" },
      { key: "TEAM_2",      label: "Team 2 name",      hint: "e.g., the Rampaging Pillows" },
      { key: "ADJ_2",       label: "Adjective",        hint: "e.g., controversial" },
      { key: "PLAYER_NAME", label: "Star player name", hint: "e.g., Brock Thunderleg" },
      { key: "VERB_3",      label: "Past tense verb",  hint: "e.g., consumed" },
      { key: "NUMBER_2",    label: "Number consumed",  hint: "e.g., seventeen" },
      { key: "FOOD",        label: "Pre-game food",    hint: "e.g., pickle" },
      { key: "RITUAL_NAME", label: "Ritual name",      hint: "e.g., The Brine Protocol" },
      { key: "ADJ_3",       label: "Adjective",        hint: "e.g., palpable" },
      { key: "NUMBER_3",    label: "Number of fans",   hint: "e.g., twelve thousand" },
      { key: "ADJ_4",       label: "Adjective",        hint: "e.g., screaming" },
      { key: "VERB_4",      label: "Verb (-ing)",      hint: "e.g., vibrating" },
      { key: "VERB_5",      label: "Verb",             hint: "e.g., score" },
      { key: "VERB_6",      label: "Verb (-ing)",      hint: "e.g., crying" },
      { key: "NUMBER_4",    label: "Overtime minutes", hint: "e.g., forty-four" },
      { key: "ADJ_5",       label: "Adjective",        hint: "e.g., quickly" },
      { key: "SCORE_1",     label: "Winning score",    hint: "e.g., 47" },
      { key: "SCORE_2",     label: "Losing score",     hint: "e.g., 46" },
      { key: "VERB_7",      label: "Past tense verb",  hint: "e.g., predicted" },
    ]
  },

  video_game_tournament: {
    title: "The Video Game Tournament",
    category: "Sports & Games",
    story: "The {{GAME_NAME}} Regional Championship at {{VENUE_NAME}} attracted {{NUMBER_1}} competitors, including {{PLAYER_1}} — a {{ADJ_1}} {{AGE}}-year-old who plays under the name \"{{GAMERTAG_1}}\" — and the reigning champion {{PLAYER_2}}, also known as \"{{GAMERTAG_2}},\" who famously once {{VERB_1}}ed for {{NUMBER_2}} hours straight to practice. The tournament was broadcast to {{NUMBER_3}} viewers who watched {{COMMENTATOR}} describe each move in a {{ADJ_2}} voice. In the final round, {{PLAYER_1}} executed a {{ADJ_3}} move called the {{MOVE_NAME}}, which {{PLAYER_2}} had never {{VERB_2}}ed before. The crowd — mostly {{ADJ_4}} teenagers — went {{ADJ_5}}. {{PLAYER_1}} won, accepted the trophy and {{PRIZE}}, and immediately {{VERB_3}}ed home to {{VERB_4}} more.",
    fields: [
      { key: "GAME_NAME",   label: "Game title",       hint: "e.g., Cosmic Blaster 7" },
      { key: "VENUE_NAME",  label: "Venue name",       hint: "e.g., Convention Center C" },
      { key: "NUMBER_1",    label: "Competitors",      hint: "e.g., two hundred" },
      { key: "PLAYER_1",    label: "Underdog player",  hint: "e.g., Reggie" },
      { key: "ADJ_1",       label: "Adjective",        hint: "e.g., underestimated" },
      { key: "AGE",         label: "Player's age",     hint: "e.g., fourteen" },
      { key: "GAMERTAG_1",  label: "Gamertag 1",       hint: "e.g., XxSnackMasterxX" },
      { key: "PLAYER_2",    label: "Champion player",  hint: "e.g., Konstantin" },
      { key: "GAMERTAG_2",  label: "Gamertag 2",       hint: "e.g., DoomBringer99" },
      { key: "VERB_1",      label: "Past tense verb",  hint: "e.g., practiced" },
      { key: "NUMBER_2",    label: "Practice hours",   hint: "e.g., seventy-two" },
      { key: "NUMBER_3",    label: "Viewers",          hint: "e.g., eighty thousand" },
      { key: "COMMENTATOR", label: "Commentator name", hint: "e.g., Chad Extreme" },
      { key: "ADJ_2",       label: "Adjective",        hint: "e.g., hysterically loud" },
      { key: "ADJ_3",       label: "Adjective",        hint: "e.g., legendary" },
      { key: "MOVE_NAME",   label: "Special move name",hint: "e.g., The Infinite Snack Loop" },
      { key: "VERB_2",      label: "Past tense verb",  hint: "e.g., seen" },
      { key: "ADJ_4",       label: "Adjective",        hint: "e.g., sleep-deprived" },
      { key: "ADJ_5",       label: "Adjective",        hint: "e.g., feral" },
      { key: "PRIZE",       label: "Tournament prize", hint: "e.g., a gift card to Best Buy" },
      { key: "VERB_3",      label: "Past tense verb",  hint: "e.g., sprinted" },
      { key: "VERB_4",      label: "Verb",             hint: "e.g., practice" },
    ]
  },

  little_league: {
    title: "Little League Chaos",
    category: "Sports & Games",
    story: "The {{TEAM_NAME}} were {{NUMBER_1}} games into their season with a record of {{WINS}} and {{LOSSES}} when coach {{COACH_NAME}} decided to shake things up. The problem was clear: {{PLAYER_1}} was {{VERB_1}}ing the wrong direction {{NUMBER_2}} percent of the time, {{PLAYER_2}} had spent three innings {{VERB_2}}ing at a {{NOUN_1}} in the outfield, and {{PLAYER_3}} had brought a {{FOOD}} to second base \"for energy.\" Coach {{COACH_NAME}} called a {{ADJ_1}} huddle and delivered a speech about {{NOUN_2}} that made {{NUMBER_3}} kids cry and {{NUMBER_4}} laugh. The final inning, the team was down by {{SCORE_DEFICIT}} when {{PLAYER_4}} — who had never {{VERB_3}}ed successfully all season — stepped up and hit the ball so {{ADJ_2}} it sailed over the {{NOUN_3}} and landed in {{PLACE}}. Pure {{ADJ_3}} chaos.",
    fields: [
      { key: "TEAM_NAME",   label: "Team name",        hint: "e.g., The Flailing Eagles" },
      { key: "NUMBER_1",    label: "Games played",     hint: "e.g., eight" },
      { key: "WINS",        label: "Wins",             hint: "e.g., one" },
      { key: "LOSSES",      label: "Losses",           hint: "e.g., seven" },
      { key: "COACH_NAME",  label: "Coach's name",     hint: "e.g., Coach Brickface" },
      { key: "PLAYER_1",    label: "Player 1 name",    hint: "e.g., Ollie" },
      { key: "VERB_1",      label: "Verb (-ing)",      hint: "e.g., running" },
      { key: "NUMBER_2",    label: "Percentage",       hint: "e.g., forty" },
      { key: "PLAYER_2",    label: "Player 2 name",    hint: "e.g., Bea" },
      { key: "VERB_2",      label: "Verb (-ing)",      hint: "e.g., staring" },
      { key: "NOUN_1",      label: "Distraction",      hint: "e.g., butterfly" },
      { key: "PLAYER_3",    label: "Player 3 name",    hint: "e.g., Marcus" },
      { key: "FOOD",        label: "Player's food",    hint: "e.g., granola bar" },
      { key: "ADJ_1",       label: "Adjective",        hint: "e.g., emotional" },
      { key: "NOUN_2",      label: "Speech topic",     hint: "e.g., believing in yourself" },
      { key: "NUMBER_3",    label: "Kids who cried",   hint: "e.g., four" },
      { key: "NUMBER_4",    label: "Kids who laughed", hint: "e.g., three" },
      { key: "SCORE_DEFICIT",label: "Points behind",   hint: "e.g., six" },
      { key: "PLAYER_4",    label: "Hero player name", hint: "e.g., tiny Gertrude" },
      { key: "VERB_3",      label: "Verb (sport skill)",hint: "e.g., hit the ball" },
      { key: "ADJ_2",       label: "Adjective",        hint: "e.g., magnificently" },
      { key: "NOUN_3",      label: "Outfield obstacle",hint: "e.g., refreshment stand" },
      { key: "PLACE",       label: "Ball landing spot",hint: "e.g., the parking lot" },
      { key: "ADJ_3",       label: "Adjective",        hint: "e.g., beautiful" },
    ]
  },

  board_game_night: {
    title: "Board Game Night Disaster",
    category: "Sports & Games",
    story: "What began as a {{ADJ_1}} board game night at {{HOST_NAME}}'s apartment descended into {{ADJ_2}} chaos during the fifth round of {{GAME_NAME}}. The rules — which nobody had fully {{VERB_1}}ed — became the subject of a {{NUMBER_1}}-minute argument between {{PLAYER_1}}, who had {{VERB_2}}ed the rulebook as a child, and {{PLAYER_2}}, who was {{ADJ_3}} about {{RULE_DISPUTE}}. {{PLAYER_3}} secretly {{VERB_3}}ed during a bathroom break, which {{PLAYER_4}} {{VERB_4}}ed at {{TIME}}. The resulting standoff lasted {{NUMBER_2}} minutes and was only resolved when {{HOST_NAME}} bribed everyone with {{FOOD}}. The final winner — {{PLAYER_5}}, who had said {{NUMBER_3}} words all night — {{VERB_5}}ed silently and pocketed their {{PRIZE}}. Everyone agreed to play {{NEXT_GAME}} next time, which will also {{VERB_6}} in disaster.",
    fields: [
      { key: "ADJ_1",       label: "Adjective",        hint: "e.g., casual" },
      { key: "HOST_NAME",   label: "Host's name",      hint: "e.g., Dave" },
      { key: "ADJ_2",       label: "Adjective",        hint: "e.g., unprecedented" },
      { key: "GAME_NAME",   label: "Game name",        hint: "e.g., Settlers of Catan" },
      { key: "VERB_1",      label: "Past tense verb",  hint: "e.g., read" },
      { key: "NUMBER_1",    label: "Argument minutes", hint: "e.g., twenty-three" },
      { key: "PLAYER_1",    label: "Rules lawyer name",hint: "e.g., Sandra" },
      { key: "VERB_2",      label: "Past tense verb",  hint: "e.g., memorized" },
      { key: "PLAYER_2",    label: "Rule disputer",    hint: "e.g., Kevin" },
      { key: "ADJ_3",       label: "Adjective",        hint: "e.g., very confident" },
      { key: "RULE_DISPUTE",label: "Disputed rule",    hint: "e.g., road placement" },
      { key: "PLAYER_3",    label: "Cheater name",     hint: "e.g., Theresa" },
      { key: "VERB_3",      label: "Past tense verb",  hint: "e.g., rearranged tiles" },
      { key: "PLAYER_4",    label: "Caught them",      hint: "e.g., Marcus" },
      { key: "VERB_4",      label: "Past tense verb",  hint: "e.g., noticed" },
      { key: "TIME",        label: "Time caught",      hint: "e.g., 10:48 PM" },
      { key: "NUMBER_2",    label: "Standoff minutes", hint: "e.g., forty" },
      { key: "FOOD",        label: "Bribery food",     hint: "e.g., chips and dip" },
      { key: "PLAYER_5",    label: "Silent winner",    hint: "e.g., Norm" },
      { key: "NUMBER_3",    label: "Words said",       hint: "e.g., eleven" },
      { key: "VERB_5",      label: "Past tense verb",  hint: "e.g., smiled" },
      { key: "PRIZE",       label: "Winner's prize",   hint: "e.g., the small trophy" },
      { key: "NEXT_GAME",   label: "Next game chosen", hint: "e.g., Monopoly" },
      { key: "VERB_6",      label: "Verb",             hint: "e.g., end" },
    ]
  },

  gym_motivation: {
    title: "New Year's Gym Resolution",
    category: "Sports & Games",
    story: "{{NAME_1}} arrived at {{GYM_NAME}} on {{DATE}} with a {{ADJ_1}} new water bottle, a playlist called \"{{PLAYLIST_NAME}},\" and a workout plan that called for {{NUMBER_1}} {{EXERCISE_1}}s, {{NUMBER_2}} {{EXERCISE_2}}s, and something called a \"{{FAKE_EXERCISE}}.\" The personal trainer, {{TRAINER_NAME}}, evaluated the plan and described it as \"{{ADJ_2}}\" before {{VERB_1}}ing it entirely and replacing it with {{NUMBER_3}} minutes of {{EXERCISE_3}}. By minute {{NUMBER_4}}, {{NAME_1}}'s {{BODY_PART}} was {{VERB_2}}ing in a way that seemed {{ADJ_3}}. The gym was full of {{NUMBER_5}} other {{ADJ_4}} resolution-makers, all {{VERB_3}}ing with varying degrees of {{NOUN_1}}. {{NAME_1}} declared the session {{ADJ_5}} and promised to come back on {{DAY_OF_WEEK}}, which absolutely happened.",
    fields: [
      { key: "NAME_1",       label: "Gym-goer's name",hint: "e.g., Reggie" },
      { key: "GYM_NAME",     label: "Gym name",       hint: "e.g., IronWill Fitness" },
      { key: "DATE",         label: "Date",           hint: "e.g., January 2nd" },
      { key: "ADJ_1",        label: "Adjective",      hint: "e.g., optimistic" },
      { key: "PLAYLIST_NAME",label: "Playlist name",  hint: "e.g., ABSOLUTE DESTRUCTION VOL. 4" },
      { key: "NUMBER_1",     label: "Number of first exercise",hint: "e.g., fifty" },
      { key: "EXERCISE_1",   label: "Exercise 1",     hint: "e.g., pull-up" },
      { key: "NUMBER_2",     label: "Number of second exercise",hint: "e.g., hundred" },
      { key: "EXERCISE_2",   label: "Exercise 2",     hint: "e.g., burpee" },
      { key: "FAKE_EXERCISE",label: "Made-up exercise",hint: "e.g., lateral lunge-twirl" },
      { key: "TRAINER_NAME", label: "Trainer's name", hint: "e.g., Chad" },
      { key: "ADJ_2",        label: "Adjective",      hint: "e.g., ambitious" },
      { key: "VERB_1",       label: "Past tense verb",hint: "e.g., deleted" },
      { key: "NUMBER_3",     label: "Minutes of exercise",hint: "e.g., eight" },
      { key: "EXERCISE_3",   label: "Humbling exercise",hint: "e.g., walking" },
      { key: "NUMBER_4",     label: "Minute it hurt", hint: "e.g., three" },
      { key: "BODY_PART",    label: "Body part",      hint: "e.g., left knee" },
      { key: "VERB_2",       label: "Verb (-ing)",    hint: "e.g., crackling" },
      { key: "ADJ_3",        label: "Adjective",      hint: "e.g., concerning" },
      { key: "NUMBER_5",     label: "Other gym-goers",hint: "e.g., forty-seven" },
      { key: "ADJ_4",        label: "Adjective",      hint: "e.g., equally hopeful" },
      { key: "VERB_3",       label: "Verb (-ing)",    hint: "e.g., suffering" },
      { key: "NOUN_1",       label: "Abstract quality",hint: "e.g., commitment" },
      { key: "ADJ_5",        label: "Adjective",      hint: "e.g., complete" },
      { key: "DAY_OF_WEEK",  label: "Day",            hint: "e.g., Wednesday" },
    ]
  },

});
