window.MADLIB_TEMPLATES = window.MADLIB_TEMPLATES || {};
Object.assign(window.MADLIB_TEMPLATES, {

  origin_story: {
    title: "The Superhero Origin Story",
    category: "Superheroes & Villains",
    story: "Nobody suspected that {{NAME_1}}, a {{ADJ_1}} {{OCCUPATION}} from {{CITY_1}}, would one day become {{HERO_NAME}}. The transformation happened on a {{ADJ_2}} {{DAY_OF_WEEK}} when {{NAME_1}} was {{VERB_1}}ing in the {{PLACE_1}} and was accidentally {{VERB_2}}ed by a {{ADJ_3}} burst of {{POWER_SOURCE}}. The side effects were {{ADJ_4}}: {{NAME_1}} now had the ability to {{SUPERPOWER_1}}, an inexplicable craving for {{FOOD}}, and a {{ADJ_5}} glow that made sleeping {{ADJ_6}}. Their first act as a hero was {{VERB_3}}ing a {{NOUN_1}} outside the {{PLACE_2}}, which {{NUMBER_1}} bystanders filmed on their phones. The costume was {{ADJ_7}} — mostly because it was just {{NOUN_2}} repurposed into a {{NOUN_3}}. But the city of {{CITY_1}} slept {{ADJ_8}}ly, which was {{NUMBER_2}} percent better than before.",
    fields: [
      { key: "NAME_1",       label: "Hero's real name",  hint: "e.g., Ned Bumble" },
      { key: "ADJ_1",        label: "Adjective",         hint: "e.g., unremarkable" },
      { key: "OCCUPATION",   label: "Day job",           hint: "e.g., accountant" },
      { key: "CITY_1",       label: "City",              hint: "e.g., Grisham Falls" },
      { key: "HERO_NAME",    label: "Superhero name",    hint: "e.g., The Unassuming Fist" },
      { key: "ADJ_2",        label: "Adjective",         hint: "e.g., unremarkable" },
      { key: "DAY_OF_WEEK",  label: "Day of week",       hint: "e.g., Tuesday" },
      { key: "VERB_1",       label: "Verb (-ing)",       hint: "e.g., grocery shopping" },
      { key: "PLACE_1",      label: "Place",             hint: "e.g., parking garage" },
      { key: "VERB_2",       label: "Past tense verb",   hint: "e.g., zapped" },
      { key: "ADJ_3",        label: "Adjective",         hint: "e.g., mysterious" },
      { key: "POWER_SOURCE", label: "Power source",      hint: "e.g., radioactive pudding" },
      { key: "ADJ_4",        label: "Adjective",         hint: "e.g., inconvenient" },
      { key: "SUPERPOWER_1", label: "Superpower",        hint: "e.g., become very slightly invisible" },
      { key: "FOOD",         label: "Food craving",      hint: "e.g., pickles" },
      { key: "ADJ_5",        label: "Adjective",         hint: "e.g., faint blue" },
      { key: "ADJ_6",        label: "Adjective",         hint: "e.g., complicated" },
      { key: "VERB_3",       label: "Verb (-ing)",       hint: "e.g., rescuing" },
      { key: "NOUN_1",       label: "Thing rescued",     hint: "e.g., runaway shopping cart" },
      { key: "PLACE_2",      label: "Location",          hint: "e.g., Trader Joe's" },
      { key: "NUMBER_1",     label: "Bystanders filming",hint: "e.g., eleven" },
      { key: "ADJ_7",        label: "Adjective",         hint: "e.g., budget" },
      { key: "NOUN_2",       label: "Repurposed material",hint: "e.g., a onesie" },
      { key: "NOUN_3",       label: "Costume type",      hint: "e.g., cape-suit" },
      { key: "ADJ_8",        label: "Adjective",         hint: "e.g., slightly" },
      { key: "NUMBER_2",     label: "Percent improvement",hint: "e.g., twelve" },
    ]
  },

  villain_monologue: {
    title: "The Villain's Monologue",
    category: "Superheroes & Villains",
    story: "\"At last, {{HERO_NAME}},\" announced {{VILLAIN_NAME}}, pacing {{ADJ_1}}ly across their {{ADJ_2}} lair, \"you have fallen into my {{ADJ_3}} trap!\" The trap was, objectively, {{ADJ_4}}: {{HERO_NAME}} was suspended from the ceiling in a {{NOUN_1}} by {{NUMBER_1}} feet of {{MATERIAL}}. \"You see,\" {{VILLAIN_NAME}} continued, adjusting their {{ADJ_5}} {{NOUN_2}}, \"it all began when {{BACKSTORY}}. And now — {{NUMBER_2}} years later — my {{NOUN_3}} is nearly complete.\" {{HERO_NAME}} had been counting. {{VILLAIN_NAME}} had been {{VERB_1}}ing for {{NUMBER_3}} minutes without a breath. \"Don't you want to know my plan?\" {{VILLAIN_NAME}} asked. \"I was hoping you'd {{VERB_2}},\" {{HERO_NAME}} said. The villain's face went {{COLOR}}. Nobody had ever said that before. It took {{NUMBER_4}} {{ADJ_6}} seconds to recover and resume {{VERB_3}}ing.",
    fields: [
      { key: "HERO_NAME",   label: "Hero's name",       hint: "e.g., Titanium Ned" },
      { key: "VILLAIN_NAME",label: "Villain's name",    hint: "e.g., Dr. Catastrophe" },
      { key: "ADJ_1",       label: "Adjective",         hint: "e.g., dramatically" },
      { key: "ADJ_2",       label: "Adjective",         hint: "e.g., unnecessarily elaborate" },
      { key: "ADJ_3",       label: "Adjective",         hint: "e.g., ingenious" },
      { key: "ADJ_4",       label: "Adjective",         hint: "e.g., surprisingly effective" },
      { key: "NOUN_1",      label: "Containment device",hint: "e.g., net" },
      { key: "NUMBER_1",    label: "Feet of material",  hint: "e.g., forty" },
      { key: "MATERIAL",    label: "Material",          hint: "e.g., dental floss" },
      { key: "ADJ_5",       label: "Adjective",         hint: "e.g., signature" },
      { key: "NOUN_2",      label: "Villain accessory", hint: "e.g., cape" },
      { key: "BACKSTORY",   label: "Villain backstory", hint: "e.g., they ran out of croutons at the salad bar" },
      { key: "NUMBER_2",    label: "Years plotting",    hint: "e.g., twenty-three" },
      { key: "NOUN_3",      label: "Evil plan",         hint: "e.g., scheme" },
      { key: "VERB_1",      label: "Verb (-ing)",       hint: "e.g., monologuing" },
      { key: "NUMBER_3",    label: "Minutes talking",   hint: "e.g., eighteen" },
      { key: "VERB_2",      label: "Verb",              hint: "e.g., stop" },
      { key: "COLOR",       label: "Color face turns",  hint: "e.g., beet red" },
      { key: "NUMBER_4",    label: "Seconds to recover",hint: "e.g., eleven" },
      { key: "ADJ_6",       label: "Adjective",         hint: "e.g., flustered" },
      { key: "VERB_3",      label: "Verb (-ing)",       hint: "e.g., monologuing" },
    ]
  },

  superhero_day_off: {
    title: "The Superhero's Day Off",
    category: "Superheroes & Villains",
    story: "For the first time in {{NUMBER_1}} months, {{HERO_NAME}} had an actual day off. No {{VILLAIN_PLURAL}}, no {{NOUN_1}}s to {{VERB_1}}, no {{ADJ_1}} press conferences. The plan was simple: {{ACTIVITY_1}} until noon, {{ACTIVITY_2}} in the afternoon, and a {{ADJ_2}} evening of {{ACTIVITY_3}}. By 9 AM, {{HERO_NAME}} had already {{VERB_2}}ed a {{ADJ_3}} situation at the {{PLACE_1}} — technically not a crime, but the {{NOUN_2}} was making everyone {{ADJ_4}}. By noon they had {{VERB_3}}ed into a {{ADJ_5}} dispute over a {{NOUN_3}} at the {{PLACE_2}}. The evening was going fine until the {{SIDEKICK_NAME}} texted: \"{{URGENT_TEXT}}.\" {{HERO_NAME}} {{VERB_4}}ed, put on the cape, and reflected that {{NUMBER_2}} hours off was honestly {{ADJ_6}} by superhero standards.",
    fields: [
      { key: "NUMBER_1",    label: "Months since last day off",hint: "e.g., seven" },
      { key: "HERO_NAME",   label: "Hero's name",       hint: "e.g., Crimson Falcon" },
      { key: "VILLAIN_PLURAL",label: "Villains (plural)",hint: "e.g., arch-nemeses" },
      { key: "NOUN_1",      label: "Thing to stop",     hint: "e.g., building" },
      { key: "VERB_1",      label: "Verb",              hint: "e.g., save" },
      { key: "ADJ_1",       label: "Adjective",         hint: "e.g., exhausting" },
      { key: "ACTIVITY_1",  label: "Morning activity",  hint: "e.g., sleep in" },
      { key: "ACTIVITY_2",  label: "Afternoon activity",hint: "e.g., see a movie" },
      { key: "ADJ_2",       label: "Adjective",         hint: "e.g., quiet" },
      { key: "ACTIVITY_3",  label: "Evening activity",  hint: "e.g., cooking" },
      { key: "VERB_2",      label: "Past tense verb",   hint: "e.g., intervened in" },
      { key: "ADJ_3",       label: "Adjective",         hint: "e.g., minor" },
      { key: "PLACE_1",     label: "First location",    hint: "e.g., grocery store" },
      { key: "NOUN_2",      label: "Thing causing issue",hint: "e.g., self-checkout machine" },
      { key: "ADJ_4",       label: "Adjective",         hint: "e.g., frustrated" },
      { key: "VERB_3",      label: "Past tense verb",   hint: "e.g., mediated" },
      { key: "ADJ_5",       label: "Adjective",         hint: "e.g., heated" },
      { key: "NOUN_3",      label: "Dispute subject",   hint: "e.g., parking spot" },
      { key: "PLACE_2",     label: "Second location",   hint: "e.g., farmers market" },
      { key: "SIDEKICK_NAME",label: "Sidekick's name",  hint: "e.g., Kid Magnitude" },
      { key: "URGENT_TEXT", label: "Urgent message",    hint: "e.g., Giant raccoon. Downtown. NOW." },
      { key: "VERB_4",      label: "Past tense verb",   hint: "e.g., sighed" },
      { key: "NUMBER_2",    label: "Hours off enjoyed", hint: "e.g., four" },
      { key: "ADJ_6",       label: "Adjective",         hint: "e.g., above average" },
    ]
  },

  sidekick_application: {
    title: "The Sidekick Job Interview",
    category: "Superheroes & Villains",
    story: "{{NAME_1}} had applied to be the official sidekick to {{HERO_NAME}} after seeing the ad on {{WEBSITE}}. The interview took place in a {{ADJ_1}} office above a {{NOUN_1}}. {{HERO_NAME}} reviewed {{NAME_1}}'s application, which listed relevant experience as \"{{EXPERIENCE_1}},\" \"{{EXPERIENCE_2}},\" and \"once {{VERB_1}}ed a {{NOUN_2}} without asking why.\" Skills included: {{SKILL_1}}, {{SKILL_2}}, and a {{ADJ_2}} tolerance for {{NOUN_3}}. The timed practical test required {{NAME_1}} to {{VERB_2}} a {{ADJ_3}} obstacle course in {{NUMBER_1}} seconds. {{NAME_1}} completed it in {{NUMBER_2}}, but knocked over the {{NOUN_4}} on the way out. {{HERO_NAME}} made notes. The rejection letter arrived {{NUMBER_3}} days later and said only \"{{REJECTION_LINE}}.\" {{NAME_1}} appealed and got the job.",
    fields: [
      { key: "NAME_1",        label: "Applicant's name",hint: "e.g., Wally" },
      { key: "HERO_NAME",     label: "Hero's name",     hint: "e.g., Lady Thunderstrike" },
      { key: "WEBSITE",       label: "Job site",        hint: "e.g., HeroJobs.net" },
      { key: "ADJ_1",         label: "Adjective",       hint: "e.g., secret" },
      { key: "NOUN_1",        label: "Business below",  hint: "e.g., dry cleaner" },
      { key: "EXPERIENCE_1",  label: "Past experience 1",hint: "e.g., karate class dropout" },
      { key: "EXPERIENCE_2",  label: "Past experience 2",hint: "e.g., assistant to a magician" },
      { key: "VERB_1",        label: "Past tense verb", hint: "e.g., lifted" },
      { key: "NOUN_2",        label: "Lifted object",   hint: "e.g., refrigerator" },
      { key: "SKILL_1",       label: "Skill 1",         hint: "e.g., aggressive positivity" },
      { key: "SKILL_2",       label: "Skill 2",         hint: "e.g., parallel parking a van" },
      { key: "ADJ_2",         label: "Adjective",       hint: "e.g., remarkable" },
      { key: "NOUN_3",        label: "Thing to tolerate",hint: "e.g., dramatic speeches" },
      { key: "VERB_2",        label: "Verb",            hint: "e.g., navigate" },
      { key: "ADJ_3",         label: "Adjective",       hint: "e.g., laser-filled" },
      { key: "NUMBER_1",      label: "Target time",     hint: "e.g., thirty" },
      { key: "NUMBER_2",      label: "Actual time",     hint: "e.g., forty-seven" },
      { key: "NOUN_4",        label: "Knocked over item",hint: "e.g., trophy case" },
      { key: "NUMBER_3",      label: "Days later",      hint: "e.g., six" },
      { key: "REJECTION_LINE",label: "Rejection message",hint: "e.g., Please do not contact us" },
    ]
  },

  team_meeting_heroes: {
    title: "The Superhero Team Meeting",
    category: "Superheroes & Villains",
    story: "The {{TEAM_NAME}} gathered in their {{ADJ_1}} headquarters for their {{FREQUENCY}} meeting. On the agenda: the {{INCIDENT}} situation, the broken {{NOUN_1}} on the {{NUMBER_1}}th floor, and a vote on whether {{HERO_1}}'s {{ADJ_2}} {{POWER_1}} counted as a team resource or a personal one. {{HERO_2}} arrived {{NUMBER_2}} minutes late covered in {{SUBSTANCE}}, offering only \"{{EXCUSE}}\" as explanation. {{HERO_3}} had brought {{FOOD}} to share, which immediately caused an argument about whether it was {{ADJ_3}}. The vote about {{HERO_1}}'s power ended {{NUMBER_3}} to {{NUMBER_4}} in favor of {{ADJ_4}}, which satisfied nobody. The meeting was supposed to end at {{TIME}}, but {{HERO_2}} raised a new item — \"{{NEW_ITEM}}\" — at {{TIME_2}}, and they were still there {{NUMBER_5}} hours later.",
    fields: [
      { key: "TEAM_NAME",   label: "Team name",        hint: "e.g., The Adequate Seven" },
      { key: "ADJ_1",       label: "Adjective",        hint: "e.g., surprisingly suburban" },
      { key: "FREQUENCY",   label: "Meeting frequency",hint: "e.g., biweekly" },
      { key: "INCIDENT",    label: "Recent incident",  hint: "e.g., Parking Garage Kraken" },
      { key: "NOUN_1",      label: "Broken thing",     hint: "e.g., coffee maker" },
      { key: "NUMBER_1",    label: "Floor number",     hint: "e.g., forty-second" },
      { key: "HERO_1",      label: "Hero 1 name",      hint: "e.g., Blazemaster" },
      { key: "ADJ_2",       label: "Adjective",        hint: "e.g., niche" },
      { key: "POWER_1",     label: "Hero's power",     hint: "e.g., ability to sense parking meters" },
      { key: "HERO_2",      label: "Late hero name",   hint: "e.g., Quantum Wren" },
      { key: "NUMBER_2",    label: "Minutes late",     hint: "e.g., seventeen" },
      { key: "SUBSTANCE",   label: "Sticky substance", hint: "e.g., slime" },
      { key: "EXCUSE",      label: "Late excuse",      hint: "e.g., Don't worry about it" },
      { key: "HERO_3",      label: "Food-bringer hero",hint: "e.g., Captain Sprout" },
      { key: "FOOD",        label: "Meeting snack",    hint: "e.g., kale chips" },
      { key: "ADJ_3",       label: "Adjective",        hint: "e.g., appropriate for meetings" },
      { key: "NUMBER_3",    label: "Votes for",        hint: "e.g., four" },
      { key: "NUMBER_4",    label: "Votes against",    hint: "e.g., three" },
      { key: "ADJ_4",       label: "Adjective",        hint: "e.g., shared" },
      { key: "TIME",        label: "Planned end time", hint: "e.g., 3 PM" },
      { key: "NEW_ITEM",    label: "New agenda item",  hint: "e.g., the cape dress code" },
      { key: "TIME_2",      label: "Time item raised", hint: "e.g., 4:55 PM" },
      { key: "NUMBER_5",    label: "Extra hours",      hint: "e.g., two" },
    ]
  },

});
