window.MADLIB_TEMPLATES = window.MADLIB_TEMPLATES || {};
Object.assign(window.MADLIB_TEMPLATES, {

  airport_chaos: {
    title: "Airport Adventure",
    category: "Travel & Vacation",
    story: "{{NAME_1}}'s flight to {{DESTINATION}} was supposed to board at {{TIME_1}}, which left exactly {{NUMBER_1}} minutes to get through the {{ADJ_1}} security line. The TSA agent, a {{ADJ_2}} person named {{AGENT_NAME}}, flagged {{NAME_1}}'s bag due to a {{NOUN_1}} that had been in there since {{YEAR}}. At the gate, an announcement revealed the flight had been delayed {{NUMBER_2}} hours due to \"{{EXCUSE}}.\" {{NAME_1}} claimed the {{ADJ_3}} middle seat next to a {{NOUN_2}} salesperson named {{SEATMATE}} who spent the entire wait {{VERB_1}}ing about {{TOPIC}}. When boarding finally began, {{NAME_1}} discovered their seat had been {{VERB_2}}ed to seat {{SEAT_NUMBER}}, a {{ADJ_4}} center seat in the {{NOUN_3}} row, next to someone eating {{FOOD}} out of a bag that rustled {{ADJ_5}}ly for four hours.",
    fields: [
      { key: "NAME_1",     label: "Traveler's name",   hint: "e.g., Sandra" },
      { key: "DESTINATION",label: "Destination",       hint: "e.g., Cancún" },
      { key: "TIME_1",     label: "Boarding time",     hint: "e.g., 6:45 AM" },
      { key: "NUMBER_1",   label: "Minutes to security",hint: "e.g., seven" },
      { key: "ADJ_1",      label: "Adjective",         hint: "e.g., inexplicable" },
      { key: "ADJ_2",      label: "Adjective",         hint: "e.g., extremely bored" },
      { key: "AGENT_NAME", label: "TSA agent name",    hint: "e.g., Randy" },
      { key: "NOUN_1",     label: "Flagged item",      hint: "e.g., snowglobe" },
      { key: "YEAR",       label: "Year item was packed",hint: "e.g., 2017" },
      { key: "NUMBER_2",   label: "Hours delayed",     hint: "e.g., four" },
      { key: "EXCUSE",     label: "Delay reason",      hint: "e.g., atmospheric disagreement" },
      { key: "ADJ_3",      label: "Adjective",         hint: "e.g., only remaining" },
      { key: "NOUN_2",     label: "Profession",        hint: "e.g., essential oil" },
      { key: "SEATMATE",   label: "Seatmate's name",   hint: "e.g., Blaine" },
      { key: "VERB_1",     label: "Verb (-ing)",       hint: "e.g., talking" },
      { key: "TOPIC",      label: "Conversation topic",hint: "e.g., his podcast" },
      { key: "VERB_2",     label: "Past tense verb",   hint: "e.g., reassigned" },
      { key: "SEAT_NUMBER",label: "Seat number",       hint: "e.g., 34B" },
      { key: "ADJ_4",      label: "Adjective",         hint: "e.g., non-reclining" },
      { key: "NOUN_3",     label: "Row description",   hint: "e.g., last" },
      { key: "FOOD",       label: "Smelly food",       hint: "e.g., tuna salad" },
      { key: "ADJ_5",      label: "Adjective",         hint: "e.g., aggressively" },
    ]
  },

  hotel_mixup: {
    title: "The Hotel Mix-Up",
    category: "Travel & Vacation",
    story: "{{NAME_1}} arrived at the {{HOTEL_NAME}} in {{CITY}} after a {{ADJ_1}} journey, only to be told their reservation — made {{NUMBER_1}} months ago — was under the name \"{{WRONG_NAME}}.\" The front desk agent, {{AGENT_NAME}}, was {{ADJ_2}} about the whole thing. The only available room was Suite {{SUITE_NUMBER}}, which had been recently {{VERB_1}}ed and still smelled of {{SMELL}}. The minibar contained exclusively {{FOOD_1}} and {{NUMBER_2}} tiny bottles of {{BEVERAGE}}. The TV got {{NUMBER_3}} channels, all showing the same {{ADJ_3}} {{NOUN_1}}. At midnight, someone {{VERB_2}}ed on the door — it was {{NAME_2}} from room {{ROOM_NUMBER}}, who believed they had {{NAME_1}}'s {{NOUN_2}}. They had been accidentally switched during {{INCIDENT}}. Both parties agreed this was {{ADJ_4}} and shared the minibar {{BEVERAGE}}s in {{ADJ_5}} solidarity.",
    fields: [
      { key: "NAME_1",    label: "Guest's name",      hint: "e.g., Marguerite" },
      { key: "HOTEL_NAME",label: "Hotel name",        hint: "e.g., The Grand Fiasco" },
      { key: "CITY",      label: "City",              hint: "e.g., Prague" },
      { key: "ADJ_1",     label: "Adjective",         hint: "e.g., seventeen-hour" },
      { key: "NUMBER_1",  label: "Months in advance", hint: "e.g., eight" },
      { key: "WRONG_NAME",label: "Wrong name",        hint: "e.g., Blorph Mcsnorkel" },
      { key: "AGENT_NAME",label: "Agent's name",      hint: "e.g., Hans" },
      { key: "ADJ_2",     label: "Adjective",         hint: "e.g., professionally unsympathetic" },
      { key: "SUITE_NUMBER",label: "Suite number",    hint: "e.g., 1408" },
      { key: "VERB_1",    label: "Past tense verb",   hint: "e.g., fumigated" },
      { key: "SMELL",     label: "Lingering smell",   hint: "e.g., lavender and despair" },
      { key: "FOOD_1",    label: "Minibar food",      hint: "e.g., expired crackers" },
      { key: "NUMBER_2",  label: "Number of bottles", hint: "e.g., seven" },
      { key: "BEVERAGE",  label: "Minibar beverage",  hint: "e.g., limoncello" },
      { key: "NUMBER_3",  label: "Number of channels",hint: "e.g., two" },
      { key: "ADJ_3",     label: "Adjective",         hint: "e.g., local" },
      { key: "NOUN_1",    label: "TV program",        hint: "e.g., infomercial" },
      { key: "VERB_2",    label: "Past tense verb",   hint: "e.g., knocked" },
      { key: "NAME_2",    label: "Other guest name",  hint: "e.g., Helmut" },
      { key: "ROOM_NUMBER",label: "Room number",      hint: "e.g., 312" },
      { key: "NOUN_2",    label: "Switched item",     hint: "e.g., suitcase" },
      { key: "INCIDENT",  label: "Where items switched",hint: "e.g., check-in" },
      { key: "ADJ_4",     label: "Adjective",         hint: "e.g., fine, actually" },
      { key: "ADJ_5",     label: "Adjective",         hint: "e.g., exhausted" },
    ]
  },

  road_trip: {
    title: "The Great American Road Trip",
    category: "Travel & Vacation",
    story: "The road trip from {{CITY_1}} to {{CITY_2}} was supposed to take {{NUMBER_1}} hours. By hour {{NUMBER_2}}, {{NAME_1}} had made {{NUMBER_3}} wrong turns, the GPS had announced \"recalculating\" {{NUMBER_4}} times in a {{ADJ_1}} tone, and {{NAME_2}} had eaten all the {{SNACK_1}}s designated for day two. The car had a {{ADJ_2}} noise that appeared whenever the speed exceeded {{NUMBER_5}} mph that {{NAME_1}} described as \"{{SOUND_DESCRIPTION}}.\" They stopped at a roadside attraction called \"{{ATTRACTION_NAME}}\" which turned out to be a {{ADJ_3}} {{NOUN_1}} in someone's front yard. {{NAME_2}} bought a {{ADJ_4}} {{SOUVENIR}} from the gift shop. By day {{NUMBER_6}}, the two had developed {{NUMBER_7}} new inside jokes and a {{ADJ_5}} tradition of {{VERB_1}}ing every time they crossed a state line.",
    fields: [
      { key: "CITY_1",         label: "Starting city",    hint: "e.g., Portland" },
      { key: "CITY_2",         label: "Destination city", hint: "e.g., Miami" },
      { key: "NUMBER_1",       label: "Planned hours",    hint: "e.g., twenty-two" },
      { key: "NUMBER_2",       label: "Hour of first disaster",hint: "e.g., three" },
      { key: "NAME_1",         label: "Driver's name",    hint: "e.g., Bev" },
      { key: "NUMBER_3",       label: "Wrong turns",      hint: "e.g., seven" },
      { key: "NUMBER_4",       label: "GPS recalcs",      hint: "e.g., forty" },
      { key: "ADJ_1",          label: "Adjective",        hint: "e.g., judgmental" },
      { key: "NAME_2",         label: "Passenger name",   hint: "e.g., Carl" },
      { key: "SNACK_1",        label: "Road trip snack",  hint: "e.g., gummy worm" },
      { key: "ADJ_2",          label: "Adjective",        hint: "e.g., rhythmic" },
      { key: "NUMBER_5",       label: "Speed trigger",    hint: "e.g., sixty-five" },
      { key: "SOUND_DESCRIPTION",label: "Sound description",hint: "e.g., angry teakettle" },
      { key: "ATTRACTION_NAME",label: "Attraction name",  hint: "e.g., World's Biggest Spoon" },
      { key: "ADJ_3",          label: "Adjective",        hint: "e.g., medium-sized" },
      { key: "NOUN_1",         label: "Roadside thing",   hint: "e.g., concrete sculpture" },
      { key: "ADJ_4",          label: "Adjective",        hint: "e.g., overpriced" },
      { key: "SOUVENIR",       label: "Souvenir type",    hint: "e.g., snow globe" },
      { key: "NUMBER_6",       label: "Day number",       hint: "e.g., four" },
      { key: "NUMBER_7",       label: "Inside jokes",     hint: "e.g., eleven" },
      { key: "ADJ_5",          label: "Adjective",        hint: "e.g., mandatory" },
      { key: "VERB_1",         label: "Verb (-ing)",      hint: "e.g., screaming" },
    ]
  },

  tour_guide: {
    title: "The Rogue Tour Guide",
    category: "Travel & Vacation",
    story: "The guided tour of {{CITY}} was being led by {{GUIDE_NAME}}, who had been doing this for {{NUMBER_1}} years and had {{ADJ_1}} opinions about everything. The tour was supposed to start at the {{LANDMARK_1}}, but {{GUIDE_NAME}} detoured to their {{ADJ_2}} favorite {{PLACE_TYPE}} first because, as they explained, \"the {{LANDMARK_1}} will still be {{ADJ_3}} later, but this {{NOUN_1}} is only {{ADJ_4}} for another {{NUMBER_2}} minutes.\" By noon, the group of {{NUMBER_3}} tourists had been taken to {{GUIDE_NAME}}'s dry cleaner, a {{ADJ_5}} café where {{GUIDE_NAME}} had \"{{HISTORY_CLAIM}},\" and a {{NOUN_2}} that turned out to be private property. The group unanimously rated the tour {{NUMBER_4}} stars and every single one of them would do it again.",
    fields: [
      { key: "CITY",          label: "Tour city",        hint: "e.g., Rome" },
      { key: "GUIDE_NAME",    label: "Guide's name",     hint: "e.g., Fernando" },
      { key: "NUMBER_1",      label: "Years guiding",    hint: "e.g., forty" },
      { key: "ADJ_1",         label: "Adjective",        hint: "e.g., extremely strong" },
      { key: "LANDMARK_1",    label: "Famous landmark",  hint: "e.g., Colosseum" },
      { key: "ADJ_2",         label: "Adjective",        hint: "e.g., personal" },
      { key: "PLACE_TYPE",    label: "Type of place",    hint: "e.g., alley" },
      { key: "ADJ_3",         label: "Adjective",        hint: "e.g., there" },
      { key: "NOUN_1",        label: "Special thing",    hint: "e.g., coffee" },
      { key: "ADJ_4",         label: "Adjective",        hint: "e.g., perfect" },
      { key: "NUMBER_2",      label: "Minutes",          hint: "e.g., twenty" },
      { key: "NUMBER_3",      label: "Tourists in group",hint: "e.g., twelve" },
      { key: "ADJ_5",         label: "Adjective",        hint: "e.g., tiny" },
      { key: "HISTORY_CLAIM", label: "Fake history claim",hint: "e.g., Julius Caesar proposed here" },
      { key: "NOUN_2",        label: "Last stop",        hint: "e.g., courtyard" },
      { key: "NUMBER_4",      label: "Star rating",      hint: "e.g., five" },
    ]
  },

  vacation_packing: {
    title: "The Packing Disaster",
    category: "Travel & Vacation",
    story: "{{NAME_1}} began packing for their {{NUMBER_1}}-day trip to {{DESTINATION}} the night before the {{TIME}} departure. The suitcase — a {{ADJ_1}} {{COLOR}} number — would officially hold {{NUMBER_2}} pounds. {{NAME_1}} was currently at {{NUMBER_3}} pounds and still needed to fit {{NUMBER_4}} {{ITEM_TYPE}}s, a {{ADJ_2}} {{NOUN_1}}, and a {{NOUN_2}} that seemed important but wasn't. Attempts to {{VERB_1}} the bag proved futile until {{NAME_1}} employed the {{TECHNIQUE}} method and {{VERB_2}}ed everything flat. The suitcase closed on the {{NUMBER_5}}th try. At the airport, it was {{NUMBER_6}} pounds over the limit, prompting {{NAME_1}} to {{VERB_3}} {{NUMBER_7}} items at the check-in counter, including the {{ADJ_3}} {{NOUN_3}} they had spent {{MONEY}} on specifically for this trip.",
    fields: [
      { key: "NAME_1",    label: "Packer's name",     hint: "e.g., Nora" },
      { key: "NUMBER_1",  label: "Trip length (days)",hint: "e.g., ten" },
      { key: "DESTINATION",label: "Destination",      hint: "e.g., Barcelona" },
      { key: "TIME",      label: "Departure time",    hint: "e.g., 6 AM" },
      { key: "ADJ_1",     label: "Adjective",         hint: "e.g., optimistic" },
      { key: "COLOR",     label: "Suitcase color",    hint: "e.g., neon pink" },
      { key: "NUMBER_2",  label: "Weight limit (lbs)",hint: "e.g., fifty" },
      { key: "NUMBER_3",  label: "Current weight",    hint: "e.g., eighty-seven" },
      { key: "NUMBER_4",  label: "Remaining items",   hint: "e.g., eleven" },
      { key: "ITEM_TYPE", label: "Item type",         hint: "e.g., shoe" },
      { key: "ADJ_2",     label: "Adjective",         hint: "e.g., just-in-case" },
      { key: "NOUN_1",    label: "Important item",    hint: "e.g., travel pillow" },
      { key: "NOUN_2",    label: "Questionable item", hint: "e.g., fondue set" },
      { key: "VERB_1",    label: "Verb",              hint: "e.g., close" },
      { key: "TECHNIQUE", label: "Packing technique", hint: "e.g., aggressive sitting on it" },
      { key: "VERB_2",    label: "Past tense verb",   hint: "e.g., crushed" },
      { key: "NUMBER_5",  label: "Number of tries",   hint: "e.g., nine" },
      { key: "NUMBER_6",  label: "Pounds over limit", hint: "e.g., thirty-two" },
      { key: "VERB_3",    label: "Verb",              hint: "e.g., abandon" },
      { key: "NUMBER_7",  label: "Items abandoned",   hint: "e.g., six" },
      { key: "ADJ_3",     label: "Adjective",         hint: "e.g., special-occasion" },
      { key: "NOUN_3",    label: "Abandoned item",    hint: "e.g., hat" },
      { key: "MONEY",     label: "Money spent",       hint: "e.g., $200" },
    ]
  },

  cruise_ship: {
    title: "All Aboard the Cruise Ship",
    category: "Travel & Vacation",
    story: "Day one aboard the {{SHIP_NAME}} and {{NAME_1}} had already {{VERB_1}}ed at the buffet {{NUMBER_1}} times, placed {{NUMBER_2}} tokens in the {{NOUN_1}} machine, and accidentally {{VERB_2}}ed onto the {{ADJ_1}} adult swim time. Their cabin — Deck {{NUMBER_3}}, Room {{ROOM_NUMBER}} — was {{ADJ_2}} but adjacent to the engine, which made a sound like {{SOUND_DESCRIPTION}} all night. By day three, {{NAME_1}} was on a first-name basis with {{NAME_2}}, the {{ADJ_3}} activities director, who insisted on {{VERB_3}}ing {{NAME_1}} into every organized event including the {{EVENT_NAME}}, a {{ADJ_4}} competition that {{NAME_1}} won despite never having {{VERB_4}}ed before. The excursion on day five involved a {{ADJ_5}} {{NOUN_2}} that got {{NUMBER_4}} minutes off course. {{NAME_1}} wrote it up as the best vacation of their life and immediately booked the next cruise.",
    fields: [
      { key: "SHIP_NAME",     label: "Cruise ship name",hint: "e.g., SS Excessive" },
      { key: "NAME_1",        label: "Passenger name",  hint: "e.g., Hector" },
      { key: "VERB_1",        label: "Past tense verb", hint: "e.g., returned" },
      { key: "NUMBER_1",      label: "Buffet visits",   hint: "e.g., seven" },
      { key: "NUMBER_2",      label: "Tokens spent",    hint: "e.g., forty" },
      { key: "NOUN_1",        label: "Machine type",    hint: "e.g., slot" },
      { key: "VERB_2",        label: "Past tense verb", hint: "e.g., wandered" },
      { key: "ADJ_1",         label: "Adjective",       hint: "e.g., reserved" },
      { key: "NUMBER_3",      label: "Deck number",     hint: "e.g., seven" },
      { key: "ROOM_NUMBER",   label: "Cabin number",    hint: "e.g., 7142" },
      { key: "ADJ_2",         label: "Adjective",       hint: "e.g., cozy" },
      { key: "SOUND_DESCRIPTION",label: "Sound desc",   hint: "e.g., angry dishwasher" },
      { key: "NAME_2",        label: "Activities director",hint: "e.g., Raoul" },
      { key: "ADJ_3",         label: "Adjective",       hint: "e.g., relentlessly cheerful" },
      { key: "VERB_3",        label: "Verb (-ing)",     hint: "e.g., recruiting" },
      { key: "EVENT_NAME",    label: "Event name",      hint: "e.g., Shuffleboard Invitational" },
      { key: "ADJ_4",         label: "Adjective",       hint: "e.g., surprisingly competitive" },
      { key: "VERB_4",        label: "Past tense verb", hint: "e.g., played shuffleboard" },
      { key: "ADJ_5",         label: "Adjective",       hint: "e.g., scenic" },
      { key: "NOUN_2",        label: "Excursion type",  hint: "e.g., catamaran" },
      { key: "NUMBER_4",      label: "Minutes off course",hint: "e.g., forty-five" },
    ]
  },

});
