window.MADLIB_TEMPLATES = window.MADLIB_TEMPLATES || {};
Object.assign(window.MADLIB_TEMPLATES, {

  performance_review: {
    title: "The Annual Performance Review",
    category: "Work & Office Life",
    story: "{{NAME_1}}'s annual performance review with manager {{MANAGER_NAME}} began {{ADJ_1}}ly enough, but took a turn when {{MANAGER_NAME}} opened with: \"Let's talk about the {{NOUN_1}} incident.\" {{NAME_1}} had hoped everyone had forgotten about that. According to the review form, {{NAME_1}} had \"exceeded expectations\" in {{SKILL_1}}, shown \"room for growth\" in {{SKILL_2}}, and demonstrated \"unique initiative\" in {{INCIDENT}}, which management was still {{VERB_1}}ing about three months later. The discussion of salary was {{ADJ_2}}. {{MANAGER_NAME}} offered a {{PERCENT}}% raise, described it as \"{{ADJ_3}},\" and slid a {{ADJ_4}} document across the table. {{NAME_1}} {{VERB_2}}ed it, {{VERB_3}}ed professionally, and spent the elevator ride composing a {{ADJ_5}} resignation letter that they did not actually send.",
    fields: [
      { key: "NAME_1",      label: "Employee name",    hint: "e.g., Brenda" },
      { key: "MANAGER_NAME",label: "Manager's name",   hint: "e.g., Skip" },
      { key: "ADJ_1",       label: "Adjective",        hint: "e.g., innocuously" },
      { key: "NOUN_1",      label: "Work incident",    hint: "e.g., printer" },
      { key: "SKILL_1",     label: "Strength skill",   hint: "e.g., synergy alignment" },
      { key: "SKILL_2",     label: "Weakness skill",   hint: "e.g., not sighing audibly" },
      { key: "INCIDENT",    label: "Memorable incident",hint: "e.g., rearranging the break room" },
      { key: "VERB_1",      label: "Verb (-ing)",      hint: "e.g., talking" },
      { key: "ADJ_2",       label: "Adjective",        hint: "e.g., brief" },
      { key: "PERCENT",     label: "Raise percentage", hint: "e.g., 1.5" },
      { key: "ADJ_3",       label: "Adjective",        hint: "e.g., competitive" },
      { key: "ADJ_4",       label: "Adjective",        hint: "e.g., laminated" },
      { key: "VERB_2",      label: "Past tense verb",  hint: "e.g., signed" },
      { key: "VERB_3",      label: "Past tense verb",  hint: "e.g., smiled" },
      { key: "ADJ_5",       label: "Adjective",        hint: "e.g., eloquent" },
    ]
  },

  office_meeting: {
    title: "This Meeting Could Have Been an Email",
    category: "Work & Office Life",
    story: "{{COMPANY_NAME}}'s {{DAY_OF_WEEK}} all-hands meeting was supposed to last {{NUMBER_1}} minutes. {{NUMBER_2}} hours later, {{NAME_1}} was still {{VERB_1}}ing through a {{NUMBER_3}}-slide presentation titled \"{{PRESENTATION_TITLE}}.\" The slide deck featured {{NUMBER_4}} pie charts, a {{ADJ_1}} stock photo of {{NOUN_1}}, and a graph that nobody — including {{NAME_1}} — could explain. Attendee {{NAME_2}} had been {{VERB_2}}ing for forty minutes under the guise of \"taking notes.\" {{NAME_3}} submitted {{NUMBER_5}} questions in the Q&A chat, all variations of \"have we considered {{NOUN_2}}?\" The meeting ended with {{NAME_1}} announcing the next meeting to discuss the outcomes of this meeting, which would be held on {{DAY_OF_WEEK_2}} at {{TIME}}. Everyone {{VERB_3}}ed {{ADJ_2}}ly.",
    fields: [
      { key: "COMPANY_NAME",      label: "Company name",     hint: "e.g., Synergy Corp" },
      { key: "DAY_OF_WEEK",       label: "Day of week",      hint: "e.g., Monday" },
      { key: "NUMBER_1",          label: "Planned minutes",  hint: "e.g., thirty" },
      { key: "NUMBER_2",          label: "Actual hours",     hint: "e.g., three" },
      { key: "NAME_1",            label: "Presenter name",   hint: "e.g., Craig" },
      { key: "VERB_1",            label: "Verb (-ing)",      hint: "e.g., presenting" },
      { key: "NUMBER_3",          label: "Number of slides", hint: "e.g., ninety-four" },
      { key: "PRESENTATION_TITLE",label: "Presentation title",hint: "e.g., Q3 Synergy Realignment" },
      { key: "NUMBER_4",          label: "Number of charts", hint: "e.g., twelve" },
      { key: "ADJ_1",             label: "Adjective",        hint: "e.g., inspirational" },
      { key: "NOUN_1",            label: "Stock photo subject",hint: "e.g., people high-fiving" },
      { key: "NAME_2",            label: "Sleeping attendee",hint: "e.g., Gerald" },
      { key: "VERB_2",            label: "Verb (-ing)",      hint: "e.g., napping" },
      { key: "NAME_3",            label: "Question person",  hint: "e.g., Linda" },
      { key: "NUMBER_5",          label: "Questions asked",  hint: "e.g., eleven" },
      { key: "NOUN_2",            label: "Unhelpful suggestion",hint: "e.g., blockchain" },
      { key: "DAY_OF_WEEK_2",     label: "Next meeting day", hint: "e.g., Friday" },
      { key: "TIME",              label: "Meeting time",     hint: "e.g., 4:45 PM" },
      { key: "VERB_3",            label: "Past tense verb",  hint: "e.g., logged off" },
      { key: "ADJ_2",             label: "Adjective",        hint: "e.g., wearily" },
    ]
  },

  first_day: {
    title: "First Day on the Job",
    category: "Work & Office Life",
    story: "{{NAME_1}}'s first day at {{COMPANY_NAME}} started when they {{VERB_1}}ed through the wrong door and ended up in the {{ROOM_NAME}}. Rescued by HR coordinator {{NAME_2}}, who had a {{ADJ_1}} smile and a lanyard that said \"{{LANYARD_TEXT}},\" {{NAME_1}} received a badge that listed their name as \"{{WRONG_NAME}}\" and a {{NUMBER_1}}-page employee handbook. The desk assigned to them still had {{PREVIOUS_EMPLOYEE}}'s {{NOUN_1}}s in every drawer. The office kitchen had {{NUMBER_2}} types of {{NOUN_2}}, all labeled {{ADJ_2}}ly with people's names. By lunch, {{NAME_1}} had accidentally {{VERB_2}}ed in the CEO's private {{NOUN_3}}, replied-all on a {{ADJ_3}} email chain, and been invited to three {{ADJ_4}} committees. They were told this was a {{ADJ_5}} start.",
    fields: [
      { key: "NAME_1",          label: "New hire's name",  hint: "e.g., Paulette" },
      { key: "COMPANY_NAME",    label: "Company name",     hint: "e.g., Globex Inc." },
      { key: "VERB_1",          label: "Past tense verb",  hint: "e.g., confidently walked" },
      { key: "ROOM_NAME",       label: "Wrong room",       hint: "e.g., server closet" },
      { key: "NAME_2",          label: "HR person's name", hint: "e.g., Deborah" },
      { key: "ADJ_1",           label: "Adjective",        hint: "e.g., professionally fixed" },
      { key: "LANYARD_TEXT",    label: "Lanyard text",     hint: "e.g., I'M HERE TO HELP" },
      { key: "WRONG_NAME",      label: "Wrong name on badge",hint: "e.g., Brent" },
      { key: "NUMBER_1",        label: "Page count",       hint: "e.g., two hundred" },
      { key: "PREVIOUS_EMPLOYEE",label: "Previous employee",hint: "e.g., Dave's" },
      { key: "NOUN_1",          label: "Left-behind items",hint: "e.g., motivational mug" },
      { key: "NUMBER_2",        label: "Number of items",  hint: "e.g., fourteen" },
      { key: "NOUN_2",          label: "Kitchen item",     hint: "e.g., yogurt" },
      { key: "ADJ_2",           label: "Adjective",        hint: "e.g., aggressively" },
      { key: "VERB_2",          label: "Past tense verb",  hint: "e.g., wandered into" },
      { key: "NOUN_3",          label: "Private space",    hint: "e.g., meditation room" },
      { key: "ADJ_3",           label: "Adjective",        hint: "e.g., sensitive" },
      { key: "ADJ_4",           label: "Adjective",        hint: "e.g., mandatory fun" },
      { key: "ADJ_5",           label: "Adjective",        hint: "e.g., typical" },
    ]
  },

  team_building: {
    title: "Team Building Exercise",
    category: "Work & Office Life",
    story: "The {{COMPANY_NAME}} team building retreat at {{VENUE}} was planned by {{PLANNER_NAME}}, who described it as a \"{{ADJ_1}} opportunity for {{NOUN_1}}.\" The first activity — {{ACTIVITY_NAME}} — required every employee to {{VERB_1}} while {{VERB_2}}ing. {{NAME_1}} immediately pulled a {{BODY_PART}} and had to {{VERB_3}} for the rest of the morning. The trust fall exercise ended when {{NAME_2}} caught {{NAME_3}} but dropped their {{NOUN_2}}. The group problem-solving challenge involved {{NUMBER_1}} {{ADJ_2}} {{NOUN_3}}s and a {{ADJ_3}} rope, but nobody told team {{COLOR_1}} they were supposed to {{VERB_4}} the {{NOUN_4}}. By the evening bonfire, {{PLANNER_NAME}} was {{VERB_5}}ing into their clipboard while {{NUMBER_2}} employees had formed {{ADJ_4}} alliances that were definitely worse than before the retreat.",
    fields: [
      { key: "COMPANY_NAME",label: "Company name",     hint: "e.g., DataFlow Solutions" },
      { key: "VENUE",       label: "Retreat venue",    hint: "e.g., Camp Awkward" },
      { key: "PLANNER_NAME",label: "Planner's name",   hint: "e.g., Cindy" },
      { key: "ADJ_1",       label: "Adjective",        hint: "e.g., transformative" },
      { key: "NOUN_1",      label: "Corporate goal",   hint: "e.g., synergistic growth" },
      { key: "ACTIVITY_NAME",label: "Activity name",   hint: "e.g., The Bamboo Bridge Challenge" },
      { key: "VERB_1",      label: "Verb",             hint: "e.g., balance" },
      { key: "VERB_2",      label: "Verb (-ing)",      hint: "e.g., reciting values" },
      { key: "NAME_1",      label: "Injured employee", hint: "e.g., Phil" },
      { key: "BODY_PART",   label: "Body part",        hint: "e.g., hamstring" },
      { key: "VERB_3",      label: "Verb",             hint: "e.g., observe" },
      { key: "NAME_2",      label: "Catcher name",     hint: "e.g., Wanda" },
      { key: "NAME_3",      label: "Faller name",      hint: "e.g., Karl" },
      { key: "NOUN_2",      label: "Dropped item",     hint: "e.g., phone" },
      { key: "NUMBER_1",    label: "Number of items",  hint: "e.g., seven" },
      { key: "ADJ_2",       label: "Adjective",        hint: "e.g., color-coded" },
      { key: "NOUN_3",      label: "Challenge prop",   hint: "e.g., pool noodle" },
      { key: "ADJ_3",       label: "Adjective",        hint: "e.g., knotted" },
      { key: "COLOR_1",     label: "Team color",       hint: "e.g., blue" },
      { key: "VERB_4",      label: "Verb",             hint: "e.g., share" },
      { key: "NOUN_4",      label: "Objective",        hint: "e.g., rubber chicken" },
      { key: "VERB_5",      label: "Verb (-ing)",      hint: "e.g., quietly weeping" },
      { key: "NUMBER_2",    label: "Number of alliances",hint: "e.g., four" },
      { key: "ADJ_4",       label: "Adjective",        hint: "e.g., factions" },
    ]
  },

  out_of_office: {
    title: "The Out-of-Office Reply",
    category: "Work & Office Life",
    story: "When {{NAME_1}} set their out-of-office reply before the {{NUMBER_1}}-day vacation, they intended to write something {{ADJ_1}}. Instead, due to an autocorrect incident involving a {{NOUN_1}} and too much {{BEVERAGE}}, they sent: \"I am currently {{VERB_1}}ing and will not be available until {{DATE}}. In my absence, please contact {{NAME_2}}, who is {{ADJ_2}} and will {{VERB_2}} all urgent matters involving {{NOUN_2}}. If this is about the {{INCIDENT}}, I was {{ADJ_3}} when that happened and {{NAME_3}} can confirm. For all other inquiries, please {{VERB_3}} yourself.\" {{NAME_1}} received {{NUMBER_2}} replies before they could fix it, including one from the CEO that said only \"{{CEO_REPLY}}.\"",
    fields: [
      { key: "NAME_1",    label: "Employee name",     hint: "e.g., Shawn" },
      { key: "NUMBER_1",  label: "Vacation days",     hint: "e.g., twelve" },
      { key: "ADJ_1",     label: "Adjective",         hint: "e.g., professional" },
      { key: "NOUN_1",    label: "Household object",  hint: "e.g., autocomplete" },
      { key: "BEVERAGE",  label: "Beverage",          hint: "e.g., wine" },
      { key: "VERB_1",    label: "Verb (-ing)",       hint: "e.g., emotionally healing" },
      { key: "DATE",      label: "Return date",       hint: "e.g., never, probably" },
      { key: "NAME_2",    label: "Backup contact",    hint: "e.g., Ronda" },
      { key: "ADJ_2",     label: "Adjective",         hint: "e.g., equally unavailable" },
      { key: "VERB_2",    label: "Verb",              hint: "e.g., ignore" },
      { key: "NOUN_2",    label: "Work topic",        hint: "e.g., the budget" },
      { key: "INCIDENT",  label: "Work incident",     hint: "e.g., Q3 spreadsheet situation" },
      { key: "ADJ_3",     label: "Adjective",         hint: "e.g., definitely not there" },
      { key: "NAME_3",    label: "Witness name",      hint: "e.g., Gary" },
      { key: "VERB_3",    label: "Verb",              hint: "e.g., help" },
      { key: "NUMBER_2",  label: "Reply count",       hint: "e.g., forty-seven" },
      { key: "CEO_REPLY", label: "CEO's reply",       hint: "e.g., See me Monday." },
    ]
  },

  coworker_microwave: {
    title: "The Office Microwave Incident",
    category: "Work & Office Life",
    story: "For {{NUMBER_1}} months, the break room at {{COMPANY_NAME}} had been plagued by a {{ADJ_1}} smell coming from the communal microwave. HR sent {{NUMBER_2}} emails. Someone put up a {{ADJ_2}} sign reading \"{{SIGN_TEXT}}.\" {{NAME_1}} claimed it was {{COWORKER_1}}'s {{FOOD_1}}. {{COWORKER_1}} blamed {{COWORKER_2}}'s {{FOOD_2}} experiment. {{COWORKER_2}} posted a {{NUMBER_3}}-page formal defense including {{NUMBER_4}} witnesses. The truth was revealed when the IT guy, {{NAME_2}}, opened the microwave on {{DAY_OF_WEEK}} and found a {{ADJ_3}} {{NOUN_1}} that had been in there since {{YEAR}}. The office held a {{ADJ_4}} memorial. The microwave was {{VERB_1}}ed. A replacement arrived on {{DAY_OF_WEEK_2}}. It smells {{ADJ_5}} already.",
    fields: [
      { key: "NUMBER_1",    label: "Months of mystery",hint: "e.g., six" },
      { key: "COMPANY_NAME",label: "Company name",     hint: "e.g., TechVenture Co." },
      { key: "ADJ_1",       label: "Adjective",        hint: "e.g., mysterious" },
      { key: "NUMBER_2",    label: "Number of emails", hint: "e.g., eleven" },
      { key: "ADJ_2",       label: "Adjective",        hint: "e.g., passive-aggressive" },
      { key: "SIGN_TEXT",   label: "Sign message",     hint: "e.g., PLEASE LABEL YOUR ITEMS" },
      { key: "NAME_1",      label: "Accuser name",     hint: "e.g., Patricia" },
      { key: "COWORKER_1",  label: "Coworker 1",       hint: "e.g., Marcus" },
      { key: "FOOD_1",      label: "Accused food 1",   hint: "e.g., fish tacos" },
      { key: "COWORKER_2",  label: "Coworker 2",       hint: "e.g., Debbie" },
      { key: "FOOD_2",      label: "Accused food 2",   hint: "e.g., kimchi project" },
      { key: "NUMBER_3",    label: "Defense page count",hint: "e.g., seven" },
      { key: "NUMBER_4",    label: "Number of witnesses",hint: "e.g., three" },
      { key: "NAME_2",      label: "IT person's name", hint: "e.g., Dave" },
      { key: "DAY_OF_WEEK", label: "Discovery day",    hint: "e.g., Thursday" },
      { key: "ADJ_3",       label: "Adjective",        hint: "e.g., unidentifiable" },
      { key: "NOUN_1",      label: "Found item",       hint: "e.g., container" },
      { key: "YEAR",        label: "Year of origin",   hint: "e.g., 2019" },
      { key: "ADJ_4",       label: "Adjective",        hint: "e.g., solemn" },
      { key: "VERB_1",      label: "Past tense verb",  hint: "e.g., replaced" },
      { key: "DAY_OF_WEEK_2",label: "Replacement day", hint: "e.g., Friday" },
      { key: "ADJ_5",       label: "Adjective",        hint: "e.g., suspicious" },
    ]
  },

});
